-- +goose Up
-- Efoy core schema v1 — PostgreSQL 16 + PostGIS 3.4 + TimescaleDB 2.x
-- Conventions: UUIDv7 ids generated by the app, money in integer cents (ETB),
-- timestamps timestamptz (UTC), business dates as date in Africa/Addis_Ababa.

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS timescaledb;
CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- ========== 0. Shared helpers ==========
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END $$ LANGUAGE plpgsql;
-- +goose StatementEnd

-- ========== 1. Enumerations ==========
CREATE TYPE user_status         AS ENUM ('ACTIVE','SUSPENDED','DELETED');
CREATE TYPE app_language        AS ENUM ('am','en','om');
CREATE TYPE role_name           AS ENUM ('STUDENT_RIDER','CIVIL_SERVANT_RIDER','GUARDIAN','DRIVER',
                                         'FLEET_OWNER','INSTITUTION_ADMIN','DISPATCHER','SUPPORT_AGENT','SUPER_ADMIN');
CREATE TYPE scope_type          AS ENUM ('GLOBAL','INSTITUTION','FLEET','ZONE');
CREATE TYPE device_platform     AS ENUM ('ANDROID','IOS','WEB');
CREATE TYPE driver_source       AS ENUM ('TAXI','YANGO','INDEPENDENT');
CREATE TYPE onboarding_status   AS ENUM ('PENDING','UNDER_REVIEW','APPROVED','ACTIVE','SUSPENDED','REJECTED');
CREATE TYPE vehicle_class       AS ENUM ('MINIBUS','MIDIBUS','SEDAN','SUV');
CREATE TYPE doc_owner_type      AS ENUM ('DRIVER','VEHICLE','FLEET_OWNER','INSTITUTION');
CREATE TYPE doc_type            AS ENUM ('DRIVING_LICENCE','VEHICLE_LIBRE','INSURANCE','ANNUAL_INSPECTION',
                                         'POLICE_CLEARANCE','PHOTO','YANGO_PROFILE','TRADE_LICENCE','TIN_CERTIFICATE','OTHER');
CREATE TYPE doc_status          AS ENUM ('PENDING','UNDER_REVIEW','APPROVED','REJECTED','EXPIRED');
CREATE TYPE standby_status      AS ENUM ('SCHEDULED','ON_DUTY','ACTIVATED','COMPLETED','NO_SHOW','CANCELLED');
CREATE TYPE institution_type    AS ENUM ('SCHOOL','UNIVERSITY','GOVERNMENT_OFFICE','PRIVATE_COMPANY');
CREATE TYPE billing_mode        AS ENUM ('RIDER_PAYS','INSTITUTION_PAYS','SPLIT');
CREATE TYPE exception_kind      AS ENUM ('HOLIDAY','NO_SERVICE','EARLY_EXIT','LATE_ENTRY');
CREATE TYPE shift_direction     AS ENUM ('ENTRY','EXIT');
CREATE TYPE record_status       AS ENUM ('DRAFT','ACTIVE','INACTIVE','ARCHIVED');
CREATE TYPE rider_type          AS ENUM ('STUDENT','CIVIL_SERVANT');
CREATE TYPE plan_period         AS ENUM ('WEEKLY','MONTHLY','TERM');
CREATE TYPE subscription_status AS ENUM ('PENDING_PAYMENT','ACTIVE','PAUSED','PAST_DUE','CANCELLED','EXPIRED');
CREATE TYPE seat_status         AS ENUM ('RESERVED','ACTIVE','RELEASED');
CREATE TYPE waitlist_status     AS ENUM ('WAITING','OFFERED','ACCEPTED','EXPIRED','CANCELLED');
CREATE TYPE trip_status         AS ENUM ('SCHEDULED','DRIVER_CHECKED_IN','IN_PROGRESS','INCIDENT','HANDOVER',
                                         'COMPLETED','CANCELLED','ABORTED');
CREATE TYPE trip_stop_status    AS ENUM ('PENDING','APPROACHING','ARRIVED','DEPARTED','SKIPPED');
CREATE TYPE manifest_status     AS ENUM ('EXPECTED','ABSENT','ON_BOARD','DROPPED_OFF','NO_SHOW','TRANSFERRED');
CREATE TYPE boarding_kind       AS ENUM ('PICKED_UP','DROPPED_OFF','NO_SHOW','TRANSFERRED_OUT','TRANSFERRED_IN');
CREATE TYPE boarding_method     AS ENUM ('QR','PIN','MANUAL','NFC_CARD');
CREATE TYPE incident_type       AS ENUM ('BREAKDOWN','ACCIDENT','FLAT_TYRE','FUEL','MEDICAL','POLICE_STOP',
                                         'DRIVER_NO_SHOW','GPS_LOST','STATIONARY_ANOMALY','HARSH_EVENT','SOS','OTHER');
CREATE TYPE incident_severity   AS ENUM ('LOW','MEDIUM','HIGH','CRITICAL');
CREATE TYPE incident_status     AS ENUM ('SUSPECTED','REPORTED','DISPATCHING','ESCALATED','REPLACEMENT_EN_ROUTE',
                                         'HANDOVER_DONE','RESOLVED','DISMISSED');
CREATE TYPE incident_source     AS ENUM ('DRIVER','AUTO','RIDER_SOS','GUARDIAN_SOS','DISPATCHER');
CREATE TYPE offer_status        AS ENUM ('OFFERED','ACCEPTED','DECLINED','EXPIRED','CANCELLED');
CREATE TYPE payment_provider    AS ENUM ('TELEBIRR','CHAPA','BANK_TRANSFER','WALLET');
CREATE TYPE payment_status      AS ENUM ('CREATED','PENDING','SUCCEEDED','FAILED','CANCELLED','REFUNDED');
CREATE TYPE invoice_status      AS ENUM ('DRAFT','ISSUED','PAID','OVERDUE','VOID');
CREATE TYPE account_type        AS ENUM ('ASSET','LIABILITY','REVENUE','EXPENSE','EQUITY');
CREATE TYPE earning_kind        AS ENUM ('TRIP','STANDBY','REPLACEMENT_PREMIUM','BONUS','PENALTY','ADJUSTMENT');
CREATE TYPE payout_status       AS ENUM ('DRAFT','APPROVED','PROCESSING','PAID','FAILED');
CREATE TYPE notif_channel       AS ENUM ('PUSH','SMS','EMAIL','IN_APP');
CREATE TYPE notif_status        AS ENUM ('QUEUED','SENT','DELIVERED','READ','FAILED');
CREATE TYPE ticket_status       AS ENUM ('OPEN','IN_PROGRESS','WAITING_ON_USER','RESOLVED','CLOSED');
CREATE TYPE ticket_priority     AS ENUM ('LOW','NORMAL','HIGH','URGENT');

-- ========== 2. Identity & access ==========
CREATE TABLE users (
  id                 uuid PRIMARY KEY,
  phone_e164         text UNIQUE CHECK (phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  email              citext UNIQUE,
  password_hash      text,                                   -- argon2id, portals only
  totp_secret_enc    bytea,                                  -- encrypted with KMS key
  full_name          text NOT NULL,
  full_name_am       text,
  preferred_language app_language NOT NULL DEFAULT 'am',
  photo_key          text,
  status             user_status NOT NULL DEFAULT 'ACTIVE',
  fayda_verified_at  timestamptz,
  last_login_at      timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  deleted_at         timestamptz,
  CHECK (phone_e164 IS NOT NULL OR email IS NOT NULL)
);
CREATE TRIGGER trg_users_updated BEFORE UPDATE ON users FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE user_roles (
  id          uuid PRIMARY KEY,
  user_id     uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role        role_name NOT NULL,
  scope       scope_type NOT NULL DEFAULT 'GLOBAL',
  scope_id    uuid,                                          -- institution / fleet / zone id
  granted_by  uuid REFERENCES users(id),
  created_at  timestamptz NOT NULL DEFAULT now(),
  CHECK ((scope = 'GLOBAL') = (scope_id IS NULL))
);
CREATE UNIQUE INDEX uq_user_roles ON user_roles (user_id, role, scope, scope_id) NULLS NOT DISTINCT;

CREATE TABLE devices (
  id           uuid PRIMARY KEY,
  user_id      uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  platform     device_platform NOT NULL,
  push_token   text,
  app_version  text,
  os_version   text,
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  created_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, push_token)
);

CREATE TABLE sessions (
  id                 uuid PRIMARY KEY,
  user_id            uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  device_id          uuid REFERENCES devices(id) ON DELETE SET NULL,
  refresh_token_hash bytea NOT NULL UNIQUE,                  -- SHA-256 of the opaque token
  family_id          uuid NOT NULL,                          -- rotation family for reuse detection
  ip                 inet,
  user_agent         text,
  expires_at         timestamptz NOT NULL,
  revoked_at         timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_sessions_user ON sessions (user_id) WHERE revoked_at IS NULL;

-- ========== 3. Zones, fleet, drivers, vehicles, documents ==========
CREATE TABLE zones (
  id          uuid PRIMARY KEY,
  city        text NOT NULL DEFAULT 'Addis Ababa',
  name        text NOT NULL,
  boundary    geography(MultiPolygon, 4326) NOT NULL,
  min_standby smallint NOT NULL DEFAULT 2,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (city, name)
);
CREATE INDEX ix_zones_boundary ON zones USING GIST (boundary);

CREATE TABLE fleet_owners (
  id             uuid PRIMARY KEY,
  user_id        uuid NOT NULL UNIQUE REFERENCES users(id),
  business_name  text NOT NULL,
  tin            text UNIQUE,
  trade_licence  text,
  payout_method  payment_provider NOT NULL DEFAULT 'TELEBIRR',
  payout_account text,                                       -- tokenised/encrypted reference
  status         onboarding_status NOT NULL DEFAULT 'PENDING',
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_fleet_owners_updated BEFORE UPDATE ON fleet_owners FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE drivers (
  id                      uuid PRIMARY KEY,
  user_id                 uuid NOT NULL UNIQUE REFERENCES users(id),
  fleet_owner_id          uuid REFERENCES fleet_owners(id),
  home_zone_id            uuid REFERENCES zones(id),
  source                  driver_source NOT NULL,
  licence_number          text NOT NULL UNIQUE,
  licence_category        text NOT NULL,
  licence_expires_on      date NOT NULL,
  emergency_contact_name  text,
  emergency_contact_phone text,
  status                  onboarding_status NOT NULL DEFAULT 'PENDING',
  student_certified       boolean NOT NULL DEFAULT false,    -- background check + child-safety training done
  standby_opt_in          boolean NOT NULL DEFAULT false,
  rating_avg              numeric(3,2) NOT NULL DEFAULT 5.00 CHECK (rating_avg BETWEEN 1 AND 5),
  rating_count            integer NOT NULL DEFAULT 0,
  approved_by             uuid REFERENCES users(id),
  approved_at             timestamptz,
  suspended_reason        text,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_drivers_status ON drivers (status);
CREATE TRIGGER trg_drivers_updated BEFORE UPDATE ON drivers FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE vehicles (
  id              uuid PRIMARY KEY,
  fleet_owner_id  uuid REFERENCES fleet_owners(id),
  owner_driver_id uuid REFERENCES drivers(id),
  plate_number    text NOT NULL UNIQUE,                      -- e.g. 'AA-3-12345'
  vehicle_class   vehicle_class NOT NULL,
  make            text NOT NULL,
  model           text NOT NULL,
  year            smallint NOT NULL CHECK (year BETWEEN 1990 AND 2100),
  colour          text NOT NULL,
  passenger_seats smallint NOT NULL CHECK (passenger_seats BETWEEN 1 AND 16),
  has_seatbelts   boolean NOT NULL DEFAULT true,
  has_first_aid   boolean NOT NULL DEFAULT false,
  photo_key       text,
  status          onboarding_status NOT NULL DEFAULT 'PENDING',
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  CHECK (fleet_owner_id IS NOT NULL OR owner_driver_id IS NOT NULL)
);
CREATE TRIGGER trg_vehicles_updated BEFORE UPDATE ON vehicles FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE documents (
  id               uuid PRIMARY KEY,
  owner_type       doc_owner_type NOT NULL,
  owner_id         uuid NOT NULL,
  doc_type         doc_type NOT NULL,
  file_key         text NOT NULL,                            -- object storage key (MinIO/S3)
  sha256           bytea NOT NULL,
  doc_number       text,
  issued_on        date,
  expires_on       date,
  status           doc_status NOT NULL DEFAULT 'PENDING',
  reviewed_by      uuid REFERENCES users(id),
  reviewed_at      timestamptz,
  rejection_reason text,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_documents_owner  ON documents (owner_type, owner_id, doc_type);
CREATE INDEX ix_documents_expiry ON documents (expires_on) WHERE status = 'APPROVED';
CREATE INDEX ix_documents_review ON documents (created_at) WHERE status IN ('PENDING','UNDER_REVIEW');

CREATE TABLE driver_vehicle_assignments (
  id         uuid PRIMARY KEY,
  driver_id  uuid NOT NULL REFERENCES drivers(id),
  vehicle_id uuid NOT NULL REFERENCES vehicles(id),
  valid      tstzrange NOT NULL DEFAULT tstzrange(now(), NULL),
  is_primary boolean NOT NULL DEFAULT true,
  -- a vehicle has at most one primary driver at any moment
  EXCLUDE USING gist (vehicle_id WITH =, valid WITH &&) WHERE (is_primary)
);

CREATE TABLE standby_shifts (
  id            uuid PRIMARY KEY,
  driver_id     uuid NOT NULL REFERENCES drivers(id),
  vehicle_id    uuid NOT NULL REFERENCES vehicles(id),
  zone_id       uuid NOT NULL REFERENCES zones(id),
  service_date  date NOT NULL,
  window_period tstzrange NOT NULL,
  status        standby_status NOT NULL DEFAULT 'SCHEDULED',
  fee_cents     bigint NOT NULL DEFAULT 0 CHECK (fee_cents >= 0),
  created_at    timestamptz NOT NULL DEFAULT now(),
  EXCLUDE USING gist (driver_id WITH =, window_period WITH &&) WHERE (status <> 'CANCELLED')
);
CREATE INDEX ix_standby_zone_date ON standby_shifts (zone_id, service_date, status);

-- ========== 4. Institutions, stops, routes, shifts, calendar ==========
CREATE TABLE institutions (
  id            uuid PRIMARY KEY,
  name          text NOT NULL,
  name_am       text,
  type          institution_type NOT NULL,
  tin           text,
  address       text,
  zone_id       uuid REFERENCES zones(id),
  location      geography(Point, 4326) NOT NULL,
  campus        geography(Polygon, 4326),                    -- gate/campus geofence
  contact_name  text,
  contact_phone text,
  billing_mode  billing_mode NOT NULL DEFAULT 'RIDER_PAYS',
  status        record_status NOT NULL DEFAULT 'ACTIVE',
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_institutions_location ON institutions USING GIST (location);
CREATE TRIGGER trg_institutions_updated BEFORE UPDATE ON institutions FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE institution_schedules (
  id             uuid PRIMARY KEY,
  institution_id uuid NOT NULL REFERENCES institutions(id) ON DELETE CASCADE,
  label          text NOT NULL DEFAULT 'default',            -- e.g. 'KG', 'Grades 1-8', 'Staff'
  weekday        smallint NOT NULL CHECK (weekday BETWEEN 1 AND 7),   -- ISO: 1 = Monday
  entry_time     time NOT NULL,
  exit_time      time NOT NULL,
  CHECK (exit_time > entry_time),
  UNIQUE (institution_id, label, weekday)
);

CREATE TABLE calendar_exceptions (
  id             uuid PRIMARY KEY,
  institution_id uuid REFERENCES institutions(id) ON DELETE CASCADE,  -- NULL = city-wide public holiday
  service_date   date NOT NULL,
  kind           exception_kind NOT NULL,
  time_override  time,
  note           text,
  created_by     uuid REFERENCES users(id),
  created_at     timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_calendar_exceptions ON calendar_exceptions
  (institution_id, service_date, kind) NULLS NOT DISTINCT;

CREATE TABLE stops (
  id                uuid PRIMARY KEY,
  name              text NOT NULL,
  name_am           text,
  landmark          text,
  location          geography(Point, 4326) NOT NULL,
  geofence_radius_m smallint NOT NULL DEFAULT 80 CHECK (geofence_radius_m BETWEEN 30 AND 300),
  created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_stops_location ON stops USING GIST (location);

CREATE TABLE pricing_policies (
  id             uuid PRIMARY KEY,
  city           text NOT NULL DEFAULT 'Addis Ababa',
  vehicle_class  vehicle_class NOT NULL,
  base_fee_cents bigint NOT NULL CHECK (base_fee_cents >= 0),
  per_km_cents   bigint NOT NULL CHECK (per_km_cents >= 0),
  per_min_cents  bigint NOT NULL CHECK (per_min_cents >= 0),
  commission_bps integer NOT NULL CHECK (commission_bps BETWEEN 0 AND 5000),   -- 1500 = 15%
  min_occupancy  smallint NOT NULL CHECK (min_occupancy BETWEEN 1 AND 16),
  valid          daterange NOT NULL,
  created_by     uuid REFERENCES users(id),
  created_at     timestamptz NOT NULL DEFAULT now(),
  EXCLUDE USING gist (city WITH =, vehicle_class WITH =, valid WITH &&)
);

CREATE TABLE routes (
  id             uuid PRIMARY KEY,
  institution_id uuid NOT NULL REFERENCES institutions(id),
  zone_id        uuid REFERENCES zones(id),
  code           text NOT NULL UNIQUE,                       -- e.g. 'KZN-BOL-01'
  name           text NOT NULL,
  vehicle_class  vehicle_class NOT NULL DEFAULT 'MINIBUS',
  path           geography(LineString, 4326),                -- planned polyline from OSRM
  distance_m     integer CHECK (distance_m > 0),
  duration_s     integer CHECK (duration_s > 0),
  status         record_status NOT NULL DEFAULT 'DRAFT',
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_routes_institution ON routes (institution_id);
CREATE TRIGGER trg_routes_updated BEFORE UPDATE ON routes FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE route_stops (
  route_id         uuid NOT NULL REFERENCES routes(id) ON DELETE CASCADE,
  seq              smallint NOT NULL CHECK (seq >= 1),
  stop_id          uuid NOT NULL REFERENCES stops(id),
  planned_offset_s integer NOT NULL CHECK (planned_offset_s >= 0),   -- seconds from first stop (ENTRY order)
  PRIMARY KEY (route_id, seq),
  UNIQUE (route_id, stop_id)
);

CREATE TABLE route_shifts (
  id                 uuid PRIMARY KEY,
  route_id           uuid NOT NULL REFERENCES routes(id),
  direction          shift_direction NOT NULL,
  schedule_label     text NOT NULL DEFAULT 'default',
  weekdays           smallint[] NOT NULL DEFAULT '{1,2,3,4,5}',
  anchor_time        time NOT NULL,                          -- ENTRY: arrive-by at institution; EXIT: depart at
  capacity           smallint NOT NULL CHECK (capacity BETWEEN 1 AND 16),
  default_vehicle_id uuid REFERENCES vehicles(id),
  default_driver_id  uuid REFERENCES drivers(id),
  pricing_policy_id  uuid REFERENCES pricing_policies(id),
  status             record_status NOT NULL DEFAULT 'DRAFT',
  valid              daterange NOT NULL,
  version            bigint NOT NULL DEFAULT 1,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  UNIQUE (route_id, direction, schedule_label, anchor_time)
);
CREATE INDEX ix_route_shifts_active ON route_shifts (status) WHERE status = 'ACTIVE';
CREATE TRIGGER trg_route_shifts_updated BEFORE UPDATE ON route_shifts FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE pricing_overrides (
  id               uuid PRIMARY KEY,
  institution_id   uuid NOT NULL REFERENCES institutions(id),
  route_id         uuid REFERENCES routes(id),
  seat_price_cents bigint NOT NULL CHECK (seat_price_cents > 0),     -- per seat per trip
  valid            daterange NOT NULL,
  contract_ref     text,
  created_at       timestamptz NOT NULL DEFAULT now()
);

-- ========== 5. Riders, guardians, subscriptions, seats ==========
CREATE TABLE riders (
  id                uuid PRIMARY KEY,
  user_id           uuid UNIQUE REFERENCES users(id),        -- NULL for young children without an account
  rider_type        rider_type NOT NULL,
  institution_id    uuid NOT NULL REFERENCES institutions(id),
  full_name         text NOT NULL,
  full_name_am      text,
  grade             text,                                    -- students
  student_number    text,
  employee_number   text,                                    -- civil servants
  photo_key         text,
  home_location     geography(Point, 4326),
  qr_secret         bytea NOT NULL,                          -- per-rider HMAC key, rotated on card loss
  daily_pin_enabled boolean NOT NULL DEFAULT true,
  may_walk_home     boolean NOT NULL DEFAULT false,          -- guardian consent for unaccompanied drop-off
  status            record_status NOT NULL DEFAULT 'ACTIVE',
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (institution_id, student_number),
  UNIQUE (institution_id, employee_number)
);
CREATE INDEX ix_riders_institution ON riders (institution_id);
CREATE TRIGGER trg_riders_updated BEFORE UPDATE ON riders FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE guardian_links (
  guardian_user_id   uuid NOT NULL REFERENCES users(id),
  rider_id           uuid NOT NULL REFERENCES riders(id) ON DELETE CASCADE,
  relationship       text NOT NULL,                          -- 'mother', 'father', 'aunt', ...
  is_primary         boolean NOT NULL DEFAULT false,
  can_manage_billing boolean NOT NULL DEFAULT true,
  created_at         timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (guardian_user_id, rider_id)
);
CREATE UNIQUE INDEX uq_primary_guardian ON guardian_links (rider_id) WHERE is_primary;

CREATE TABLE authorized_pickups (
  id           uuid PRIMARY KEY,
  rider_id     uuid NOT NULL REFERENCES riders(id) ON DELETE CASCADE,
  full_name    text NOT NULL,
  phone_e164   text NOT NULL,
  relationship text NOT NULL,
  photo_key    text,
  active       boolean NOT NULL DEFAULT true,
  added_by     uuid NOT NULL REFERENCES users(id),
  created_at   timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE plans (
  id           uuid PRIMARY KEY,
  code         text NOT NULL UNIQUE,                         -- 'WEEKLY', 'MONTHLY', 'TERM'
  name         text NOT NULL,
  period       plan_period NOT NULL,
  discount_bps integer NOT NULL DEFAULT 0 CHECK (discount_bps BETWEEN 0 AND 5000),
  active       boolean NOT NULL DEFAULT true
);

CREATE TABLE subscriptions (
  id                   uuid PRIMARY KEY,
  rider_id             uuid NOT NULL REFERENCES riders(id),
  plan_id              uuid NOT NULL REFERENCES plans(id),
  payer_user_id        uuid REFERENCES users(id),
  payer_institution_id uuid REFERENCES institutions(id),
  status               subscription_status NOT NULL DEFAULT 'PENDING_PAYMENT',
  period               daterange NOT NULL,
  auto_renew           boolean NOT NULL DEFAULT true,
  price_cents          bigint NOT NULL CHECK (price_cents >= 0),
  currency             char(3) NOT NULL DEFAULT 'ETB',
  quote                jsonb NOT NULL,                       -- snapshot of pricing inputs (auditability)
  hold_expires_at      timestamptz,                          -- 15-minute seat hold while PENDING_PAYMENT
  cancelled_at         timestamptz,
  cancel_reason        text,
  version              bigint NOT NULL DEFAULT 1,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  CHECK (num_nonnulls(payer_user_id, payer_institution_id) >= 1)
);
CREATE INDEX ix_subscriptions_rider ON subscriptions (rider_id, status);
CREATE INDEX ix_subscriptions_renew ON subscriptions (upper(period)) WHERE status = 'ACTIVE' AND auto_renew;
CREATE INDEX ix_subscriptions_hold  ON subscriptions (hold_expires_at) WHERE status = 'PENDING_PAYMENT';
CREATE TRIGGER trg_subscriptions_updated BEFORE UPDATE ON subscriptions FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE seat_assignments (
  id              uuid PRIMARY KEY,
  subscription_id uuid NOT NULL REFERENCES subscriptions(id),
  route_shift_id  uuid NOT NULL REFERENCES route_shifts(id),
  rider_id        uuid NOT NULL REFERENCES riders(id),
  stop_id         uuid NOT NULL REFERENCES stops(id),
  valid           daterange NOT NULL,
  status          seat_status NOT NULL DEFAULT 'RESERVED',
  created_at      timestamptz NOT NULL DEFAULT now(),
  -- a rider cannot hold two seats on the same shift at once
  EXCLUDE USING gist (rider_id WITH =, route_shift_id WITH =, valid WITH &&) WHERE (status <> 'RELEASED')
);
CREATE INDEX ix_seats_shift ON seat_assignments (route_shift_id) WHERE status <> 'RELEASED';

-- Capacity guard (defence in depth; the service also locks the shift row).
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION enforce_shift_capacity() RETURNS trigger AS $$
DECLARE
  cap  smallint;
  used integer;
BEGIN
  IF NEW.status = 'RELEASED' THEN
    RETURN NEW;
  END IF;
  SELECT capacity INTO cap FROM route_shifts WHERE id = NEW.route_shift_id FOR UPDATE;
  SELECT count(*) INTO used
    FROM seat_assignments
   WHERE route_shift_id = NEW.route_shift_id
     AND status <> 'RELEASED'
     AND valid && NEW.valid
     AND id <> NEW.id;
  IF used >= cap THEN
    RAISE EXCEPTION 'route shift % is full (% seats)', NEW.route_shift_id, cap
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END $$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE TRIGGER trg_seat_capacity BEFORE INSERT OR UPDATE OF status, valid, route_shift_id
  ON seat_assignments FOR EACH ROW EXECUTE FUNCTION enforce_shift_capacity();

CREATE TABLE waitlist_entries (
  id               uuid PRIMARY KEY,
  route_shift_id   uuid NOT NULL REFERENCES route_shifts(id),
  rider_id         uuid NOT NULL REFERENCES riders(id),
  stop_id          uuid NOT NULL REFERENCES stops(id),
  plan_id          uuid NOT NULL REFERENCES plans(id),
  status           waitlist_status NOT NULL DEFAULT 'WAITING',
  offered_at       timestamptz,
  offer_expires_at timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_waitlist_active ON waitlist_entries (route_shift_id, rider_id)
  WHERE status IN ('WAITING','OFFERED');
CREATE INDEX ix_waitlist_queue ON waitlist_entries (route_shift_id, created_at) WHERE status = 'WAITING';

CREATE TABLE absences (
  id           uuid PRIMARY KEY,
  rider_id     uuid NOT NULL REFERENCES riders(id),
  service_date date NOT NULL,
  direction    shift_direction,                              -- NULL = both directions
  reason       text,
  created_by   uuid NOT NULL REFERENCES users(id),
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_absences ON absences (rider_id, service_date, direction) NULLS NOT DISTINCT;

-- ========== 6. Trips, manifest, boarding, tracking ==========
CREATE TABLE trips (
  id               uuid PRIMARY KEY,
  route_shift_id   uuid NOT NULL REFERENCES route_shifts(id),
  service_date     date NOT NULL,
  direction        shift_direction NOT NULL,
  vehicle_id       uuid NOT NULL REFERENCES vehicles(id),
  driver_id        uuid NOT NULL REFERENCES drivers(id),
  parent_trip_id   uuid REFERENCES trips(id),                -- set on replacement (continuation) trips
  status           trip_status NOT NULL DEFAULT 'SCHEDULED',
  planned_start_at timestamptz NOT NULL,
  planned_end_at   timestamptz NOT NULL,
  checked_in_at    timestamptz,
  actual_start_at  timestamptz,
  actual_end_at    timestamptz,
  on_board_count   smallint NOT NULL DEFAULT 0 CHECK (on_board_count BETWEEN 0 AND 16),
  distance_m       integer,
  delay_s          integer NOT NULL DEFAULT 0,
  version          bigint NOT NULL DEFAULT 1,
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now(),
  CHECK (planned_end_at > planned_start_at)
);
-- exactly one original trip per shift per day
CREATE UNIQUE INDEX uq_trips_shift_day ON trips (route_shift_id, service_date) WHERE parent_trip_id IS NULL;
CREATE INDEX ix_trips_day_status ON trips (service_date, status);
CREATE INDEX ix_trips_driver_day ON trips (driver_id, service_date);
CREATE INDEX ix_trips_live ON trips (status) WHERE status IN ('DRIVER_CHECKED_IN','IN_PROGRESS','INCIDENT','HANDOVER');
CREATE TRIGGER trg_trips_updated BEFORE UPDATE ON trips FOR EACH ROW EXECUTE FUNCTION set_updated_at();

CREATE TABLE trip_stops (
  id                 uuid PRIMARY KEY,
  trip_id            uuid NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  stop_id            uuid NOT NULL REFERENCES stops(id),
  seq                smallint NOT NULL,
  planned_arrival_at timestamptz NOT NULL,
  eta_at             timestamptz,
  arrived_at         timestamptz,
  departed_at        timestamptz,
  status             trip_stop_status NOT NULL DEFAULT 'PENDING',
  UNIQUE (trip_id, seq)
);

CREATE TABLE trip_manifest (
  trip_id            uuid NOT NULL REFERENCES trips(id) ON DELETE CASCADE,
  rider_id           uuid NOT NULL REFERENCES riders(id),
  seat_assignment_id uuid NOT NULL REFERENCES seat_assignments(id),
  stop_id            uuid NOT NULL REFERENCES stops(id),
  status             manifest_status NOT NULL DEFAULT 'EXPECTED',
  updated_at         timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (trip_id, rider_id)
);
CREATE INDEX ix_manifest_rider ON trip_manifest (rider_id);

CREATE TABLE pre_trip_checklists (
  id           uuid PRIMARY KEY,
  trip_id      uuid NOT NULL UNIQUE REFERENCES trips(id),
  driver_id    uuid NOT NULL REFERENCES drivers(id),
  items        jsonb NOT NULL,                               -- {"fuel":true,"tyres":true,"seatbelts":true,"first_aid":true}
  passed       boolean NOT NULL,
  location     geography(Point, 4326),
  submitted_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE boarding_events (
  id                  uuid PRIMARY KEY,
  trip_id             uuid NOT NULL REFERENCES trips(id),
  rider_id            uuid NOT NULL REFERENCES riders(id),
  stop_id             uuid REFERENCES stops(id),
  kind                boarding_kind NOT NULL,
  method              boarding_method NOT NULL,
  handed_to_pickup_id uuid REFERENCES authorized_pickups(id),   -- EXIT drop-offs of students
  related_trip_id     uuid REFERENCES trips(id),                -- transfer counterpart
  location            geography(Point, 4326) NOT NULL,
  device_recorded_at  timestamptz NOT NULL,
  server_recorded_at  timestamptz NOT NULL DEFAULT now(),
  recorded_by         uuid NOT NULL REFERENCES users(id),
  photo_key           text,
  UNIQUE (trip_id, rider_id, kind)                              -- idempotent retries
);
CREATE INDEX ix_boarding_rider_time ON boarding_events (rider_id, server_recorded_at DESC);

-- High-volume GPS history (TimescaleDB hypertable)
CREATE TABLE vehicle_locations (
  time                timestamptz NOT NULL,
  vehicle_id          uuid NOT NULL,
  trip_id             uuid,
  driver_id           uuid,
  location            geography(Point, 4326) NOT NULL,
  speed_kmh           real,
  heading_deg         smallint,
  accuracy_m          real,
  battery_pct         smallint,
  is_offline_backfill boolean NOT NULL DEFAULT false
);
SELECT create_hypertable('vehicle_locations', by_range('time', INTERVAL '1 day'));
CREATE INDEX ix_vloc_trip_time    ON vehicle_locations (trip_id, time DESC);
CREATE INDEX ix_vloc_vehicle_time ON vehicle_locations (vehicle_id, time DESC);
ALTER TABLE vehicle_locations SET (timescaledb.compress, timescaledb.compress_segmentby = 'vehicle_id');
SELECT add_compression_policy('vehicle_locations', INTERVAL '3 days');
SELECT add_retention_policy('vehicle_locations', INTERVAL '90 days');

-- ========== 7. Incidents & replacement ==========
CREATE TABLE incidents (
  id                  uuid PRIMARY KEY,
  trip_id             uuid REFERENCES trips(id),             -- NULL for pre-trip driver no-show on standby
  vehicle_id          uuid REFERENCES vehicles(id),
  driver_id           uuid REFERENCES drivers(id),
  type                incident_type NOT NULL,
  severity            incident_severity NOT NULL,
  status              incident_status NOT NULL,
  source              incident_source NOT NULL,
  location            geography(Point, 4326),
  description         text,
  reported_by         uuid REFERENCES users(id),
  assigned_dispatcher uuid REFERENCES users(id),
  opened_at           timestamptz NOT NULL DEFAULT now(),
  assigned_at         timestamptz,
  arrived_at          timestamptz,
  resolved_at         timestamptz,
  sla_met             boolean,
  version             bigint NOT NULL DEFAULT 1
);
CREATE INDEX ix_incidents_open ON incidents (opened_at) WHERE status NOT IN ('RESOLVED','DISMISSED');
CREATE INDEX ix_incidents_trip ON incidents (trip_id);
-- one open incident per trip at a time
CREATE UNIQUE INDEX uq_incident_open_per_trip ON incidents (trip_id)
  WHERE status NOT IN ('RESOLVED','DISMISSED') AND trip_id IS NOT NULL;

CREATE TABLE incident_events (
  id          bigserial PRIMARY KEY,
  incident_id uuid NOT NULL REFERENCES incidents(id) ON DELETE CASCADE,
  kind        text NOT NULL,                                 -- 'status_changed', 'note', 'call_placed', ...
  actor_id    uuid REFERENCES users(id),
  payload     jsonb NOT NULL DEFAULT '{}',
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_incident_events ON incident_events (incident_id, created_at);

CREATE TABLE replacement_offers (
  id            uuid PRIMARY KEY,
  incident_id   uuid NOT NULL REFERENCES incidents(id),
  driver_id     uuid NOT NULL REFERENCES drivers(id),
  vehicle_id    uuid NOT NULL REFERENCES vehicles(id),
  score         numeric(6,4) NOT NULL,
  eta_s         integer NOT NULL,
  premium_cents bigint NOT NULL DEFAULT 0,
  status        offer_status NOT NULL DEFAULT 'OFFERED',
  offered_at    timestamptz NOT NULL DEFAULT now(),
  expires_at    timestamptz NOT NULL,
  responded_at  timestamptz
);
-- only one accepted offer per incident
CREATE UNIQUE INDEX uq_offer_accepted ON replacement_offers (incident_id) WHERE status = 'ACCEPTED';

CREATE TABLE replacements (
  id                    uuid PRIMARY KEY,
  incident_id           uuid NOT NULL REFERENCES incidents(id),
  original_trip_id      uuid NOT NULL REFERENCES trips(id),
  replacement_trip_id   uuid NOT NULL UNIQUE REFERENCES trips(id),
  handover_location     geography(Point, 4326),
  arrived_at            timestamptz,
  handover_completed_at timestamptz,
  riders_transferred    smallint NOT NULL DEFAULT 0,
  created_at            timestamptz NOT NULL DEFAULT now()
);

-- ========== 8. Payments, invoices, ledger, payouts ==========
CREATE TABLE invoices (
  id             uuid PRIMARY KEY,
  number         text NOT NULL UNIQUE,                       -- 'EFY-2026-000123'
  institution_id uuid NOT NULL REFERENCES institutions(id),
  period         daterange NOT NULL,
  subtotal_cents bigint NOT NULL,
  vat_cents      bigint NOT NULL,
  total_cents    bigint NOT NULL,
  status         invoice_status NOT NULL DEFAULT 'DRAFT',
  due_on         date NOT NULL,
  pdf_key        text,
  issued_at      timestamptz,
  paid_at        timestamptz,
  created_at     timestamptz NOT NULL DEFAULT now(),
  CHECK (total_cents = subtotal_cents + vat_cents)
);

CREATE TABLE invoice_lines (
  id              uuid PRIMARY KEY,
  invoice_id      uuid NOT NULL REFERENCES invoices(id) ON DELETE CASCADE,
  subscription_id uuid REFERENCES subscriptions(id),
  description     text NOT NULL,
  quantity        integer NOT NULL DEFAULT 1,
  unit_cents      bigint NOT NULL,
  amount_cents    bigint NOT NULL
);

CREATE TABLE payment_intents (
  id              uuid PRIMARY KEY,
  subscription_id uuid REFERENCES subscriptions(id),
  invoice_id      uuid REFERENCES invoices(id),
  payer_user_id   uuid REFERENCES users(id),
  amount_cents    bigint NOT NULL CHECK (amount_cents > 0),
  currency        char(3) NOT NULL DEFAULT 'ETB',
  provider        payment_provider NOT NULL,
  provider_ref    text,                                      -- tx_ref / merchant order id
  status          payment_status NOT NULL DEFAULT 'CREATED',
  checkout_url    text,
  idempotency_key text NOT NULL UNIQUE,
  failure_reason  text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  confirmed_at    timestamptz,
  CHECK (num_nonnulls(subscription_id, invoice_id) = 1),
  UNIQUE (provider, provider_ref)
);
CREATE INDEX ix_payment_intents_pending ON payment_intents (created_at) WHERE status IN ('CREATED','PENDING');

CREATE TABLE payment_webhooks (
  id              bigserial PRIMARY KEY,
  provider        payment_provider NOT NULL,
  event_id        text NOT NULL,
  signature_valid boolean NOT NULL,
  payload         jsonb NOT NULL,
  received_at     timestamptz NOT NULL DEFAULT now(),
  processed_at    timestamptz,
  error           text,
  UNIQUE (provider, event_id)
);

CREATE TABLE ledger_accounts (
  id         uuid PRIMARY KEY,
  code       text NOT NULL UNIQUE,                           -- 'cash:telebirr', 'rider_credit:<user>', 'driver_payable:<driver>'
  type       account_type NOT NULL,
  owner_type text,
  owner_id   uuid,
  currency   char(3) NOT NULL DEFAULT 'ETB',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE ledger_transactions (
  id             uuid PRIMARY KEY,
  kind           text NOT NULL,                              -- 'subscription_payment','trip_earning','refund','payout','true_up','route_subsidy'
  reference_type text NOT NULL,
  reference_id   uuid NOT NULL,
  description    text,
  occurred_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (kind, reference_type, reference_id)                -- posting is idempotent per business event
);

CREATE TABLE ledger_entries (
  id             bigserial PRIMARY KEY,
  transaction_id uuid NOT NULL REFERENCES ledger_transactions(id),
  account_id     uuid NOT NULL REFERENCES ledger_accounts(id),
  amount_cents   bigint NOT NULL CHECK (amount_cents <> 0)   -- + debit, - credit
);
CREATE INDEX ix_ledger_entries_account ON ledger_entries (account_id);
CREATE INDEX ix_ledger_entries_tx      ON ledger_entries (transaction_id);

-- Every transaction must balance to zero (checked at COMMIT).
-- +goose StatementBegin
CREATE OR REPLACE FUNCTION assert_ledger_balanced() RETURNS trigger AS $$
DECLARE
  s bigint;
BEGIN
  SELECT COALESCE(sum(amount_cents), 0) INTO s FROM ledger_entries WHERE transaction_id = NEW.transaction_id;
  IF s <> 0 THEN
    RAISE EXCEPTION 'ledger transaction % unbalanced by % cents', NEW.transaction_id, s;
  END IF;
  RETURN NULL;
END $$ LANGUAGE plpgsql;
-- +goose StatementEnd

CREATE CONSTRAINT TRIGGER trg_ledger_balanced
  AFTER INSERT OR UPDATE ON ledger_entries
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION assert_ledger_balanced();

CREATE VIEW account_balances AS
  SELECT a.id, a.code, a.type, COALESCE(sum(e.amount_cents), 0) AS balance_cents
    FROM ledger_accounts a
    LEFT JOIN ledger_entries e ON e.account_id = a.id
   GROUP BY a.id;

CREATE TABLE payouts (
  id               uuid PRIMARY KEY,
  driver_id        uuid REFERENCES drivers(id),
  fleet_owner_id   uuid REFERENCES fleet_owners(id),
  period           daterange NOT NULL,
  gross_cents      bigint NOT NULL,
  commission_cents bigint NOT NULL,
  penalties_cents  bigint NOT NULL DEFAULT 0,
  bonuses_cents    bigint NOT NULL DEFAULT 0,
  net_cents        bigint NOT NULL,
  status           payout_status NOT NULL DEFAULT 'DRAFT',
  provider         payment_provider,
  provider_ref     text,
  approved_by      uuid REFERENCES users(id),
  paid_at          timestamptz,
  created_at       timestamptz NOT NULL DEFAULT now(),
  CHECK (num_nonnulls(driver_id, fleet_owner_id) = 1),
  CHECK (net_cents = gross_cents - commission_cents - penalties_cents + bonuses_cents)
);

CREATE TABLE driver_earnings (
  id               uuid PRIMARY KEY,
  driver_id        uuid NOT NULL REFERENCES drivers(id),
  trip_id          uuid REFERENCES trips(id),
  standby_shift_id uuid REFERENCES standby_shifts(id),
  kind             earning_kind NOT NULL,
  amount_cents     bigint NOT NULL,                          -- negative for penalties
  payout_id        uuid REFERENCES payouts(id),
  note             text,
  created_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX ix_earnings_unpaid ON driver_earnings (driver_id) WHERE payout_id IS NULL;
CREATE UNIQUE INDEX uq_earning_trip ON driver_earnings (trip_id, kind) WHERE trip_id IS NOT NULL AND kind = 'TRIP';

-- ========== 9. Notifications, ratings, support, audit, outbox ==========
CREATE TABLE notification_templates (
  code     text NOT NULL,                                    -- 'boarding.picked_up'
  channel  notif_channel NOT NULL,
  language app_language NOT NULL,
  title    text,
  body     text NOT NULL,                                    -- Go text/template syntax
  PRIMARY KEY (code, channel, language)
);

CREATE TABLE notifications (
  id            uuid PRIMARY KEY,
  user_id       uuid NOT NULL REFERENCES users(id),
  template_code text NOT NULL,
  channel       notif_channel NOT NULL,
  payload       jsonb NOT NULL,
  priority      smallint NOT NULL DEFAULT 5,                 -- 1 = safety critical
  status        notif_status NOT NULL DEFAULT 'QUEUED',
  provider_ref  text,
  attempts      smallint NOT NULL DEFAULT 0,
  dedupe_key    text UNIQUE,
  created_at    timestamptz NOT NULL DEFAULT now(),
  sent_at       timestamptz,
  delivered_at  timestamptz,
  read_at       timestamptz
);
CREATE INDEX ix_notifications_inbox ON notifications (user_id, created_at DESC) WHERE channel = 'IN_APP';

CREATE TABLE ratings (
  id            uuid PRIMARY KEY,
  trip_id       uuid NOT NULL REFERENCES trips(id),
  rater_user_id uuid NOT NULL REFERENCES users(id),
  driver_id     uuid NOT NULL REFERENCES drivers(id),
  score         smallint NOT NULL CHECK (score BETWEEN 1 AND 5),
  tags          text[] NOT NULL DEFAULT '{}',                -- 'on_time', 'safe_driving', 'rude', ...
  comment       text,
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (trip_id, rater_user_id)
);

CREATE TABLE support_tickets (
  id                uuid PRIMARY KEY,
  requester_user_id uuid NOT NULL REFERENCES users(id),
  trip_id           uuid REFERENCES trips(id),
  incident_id       uuid REFERENCES incidents(id),
  category          text NOT NULL,
  subject           text NOT NULL,
  status            ticket_status NOT NULL DEFAULT 'OPEN',
  priority          ticket_priority NOT NULL DEFAULT 'NORMAL',
  assigned_to       uuid REFERENCES users(id),
  created_at        timestamptz NOT NULL DEFAULT now(),
  resolved_at       timestamptz
);

CREATE TABLE ticket_messages (
  id          bigserial PRIMARY KEY,
  ticket_id   uuid NOT NULL REFERENCES support_tickets(id) ON DELETE CASCADE,
  author_id   uuid NOT NULL REFERENCES users(id),
  body        text NOT NULL,
  attachments text[] NOT NULL DEFAULT '{}',
  internal    boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE audit_logs (
  id          bigserial,
  actor_id    uuid,
  action      text NOT NULL,                                 -- 'driver.approve', 'pricing.update', 'rider.view_location'
  entity_type text NOT NULL,
  entity_id   uuid,
  before      jsonb,
  after       jsonb,
  ip          inet,
  request_id  text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (id, created_at)
) PARTITION BY RANGE (created_at);
CREATE TABLE audit_logs_2026_09 PARTITION OF audit_logs FOR VALUES FROM ('2026-09-01') TO ('2026-10-01');
CREATE TABLE audit_logs_2026_10 PARTITION OF audit_logs FOR VALUES FROM ('2026-10-01') TO ('2026-11-01');
CREATE TABLE audit_logs_2026_11 PARTITION OF audit_logs FOR VALUES FROM ('2026-11-01') TO ('2026-12-01');
CREATE INDEX ix_audit_entity ON audit_logs (entity_type, entity_id, created_at DESC);

CREATE TABLE outbox_events (
  id             bigserial PRIMARY KEY,
  aggregate_type text NOT NULL,
  aggregate_id   uuid NOT NULL,
  subject        text NOT NULL,                              -- NATS subject, e.g. 'efoy.boarding.picked_up'
  payload        jsonb NOT NULL,
  headers        jsonb NOT NULL DEFAULT '{}',                -- trace context, event id
  created_at     timestamptz NOT NULL DEFAULT now(),
  published_at   timestamptz
);
CREATE INDEX ix_outbox_unpublished ON outbox_events (id) WHERE published_at IS NULL;

CREATE TABLE feature_flags (
  key        text PRIMARY KEY,
  enabled    boolean NOT NULL DEFAULT false,
  rules      jsonb NOT NULL DEFAULT '{}',                    -- e.g. {"institutions": ["..."], "percent": 10}
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- +goose Down
-- Intentionally empty for the initial schema; restore from backup instead.
