// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql/driver"
	"fmt"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccountType string

const (
	AccountTypeASSET     AccountType = "ASSET"
	AccountTypeLIABILITY AccountType = "LIABILITY"
	AccountTypeREVENUE   AccountType = "REVENUE"
	AccountTypeEXPENSE   AccountType = "EXPENSE"
	AccountTypeEQUITY    AccountType = "EQUITY"
)

func (e *AccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountType(s)
	case string:
		*e = AccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountType: %T", src)
	}
	return nil
}

type NullAccountType struct {
	AccountType AccountType `json:"account_type"`
	Valid       bool        `json:"valid"` // Valid is true if AccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.AccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountType), nil
}

type AppLanguage string

const (
	AppLanguageAm AppLanguage = "am"
	AppLanguageEn AppLanguage = "en"
	AppLanguageOm AppLanguage = "om"
)

func (e *AppLanguage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AppLanguage(s)
	case string:
		*e = AppLanguage(s)
	default:
		return fmt.Errorf("unsupported scan type for AppLanguage: %T", src)
	}
	return nil
}

type NullAppLanguage struct {
	AppLanguage AppLanguage `json:"app_language"`
	Valid       bool        `json:"valid"` // Valid is true if AppLanguage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAppLanguage) Scan(value interface{}) error {
	if value == nil {
		ns.AppLanguage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AppLanguage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAppLanguage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AppLanguage), nil
}

type BillingMode string

const (
	BillingModeRIDERPAYS       BillingMode = "RIDER_PAYS"
	BillingModeINSTITUTIONPAYS BillingMode = "INSTITUTION_PAYS"
	BillingModeSPLIT           BillingMode = "SPLIT"
)

func (e *BillingMode) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BillingMode(s)
	case string:
		*e = BillingMode(s)
	default:
		return fmt.Errorf("unsupported scan type for BillingMode: %T", src)
	}
	return nil
}

type NullBillingMode struct {
	BillingMode BillingMode `json:"billing_mode"`
	Valid       bool        `json:"valid"` // Valid is true if BillingMode is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBillingMode) Scan(value interface{}) error {
	if value == nil {
		ns.BillingMode, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BillingMode.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBillingMode) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BillingMode), nil
}

type BoardingKind string

const (
	BoardingKindPICKEDUP       BoardingKind = "PICKED_UP"
	BoardingKindDROPPEDOFF     BoardingKind = "DROPPED_OFF"
	BoardingKindNOSHOW         BoardingKind = "NO_SHOW"
	BoardingKindTRANSFERREDOUT BoardingKind = "TRANSFERRED_OUT"
	BoardingKindTRANSFERREDIN  BoardingKind = "TRANSFERRED_IN"
)

func (e *BoardingKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BoardingKind(s)
	case string:
		*e = BoardingKind(s)
	default:
		return fmt.Errorf("unsupported scan type for BoardingKind: %T", src)
	}
	return nil
}

type NullBoardingKind struct {
	BoardingKind BoardingKind `json:"boarding_kind"`
	Valid        bool         `json:"valid"` // Valid is true if BoardingKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBoardingKind) Scan(value interface{}) error {
	if value == nil {
		ns.BoardingKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BoardingKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBoardingKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BoardingKind), nil
}

type BoardingMethod string

const (
	BoardingMethodQR      BoardingMethod = "QR"
	BoardingMethodPIN     BoardingMethod = "PIN"
	BoardingMethodMANUAL  BoardingMethod = "MANUAL"
	BoardingMethodNFCCARD BoardingMethod = "NFC_CARD"
)

func (e *BoardingMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BoardingMethod(s)
	case string:
		*e = BoardingMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for BoardingMethod: %T", src)
	}
	return nil
}

type NullBoardingMethod struct {
	BoardingMethod BoardingMethod `json:"boarding_method"`
	Valid          bool           `json:"valid"` // Valid is true if BoardingMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBoardingMethod) Scan(value interface{}) error {
	if value == nil {
		ns.BoardingMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BoardingMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBoardingMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BoardingMethod), nil
}

type DevicePlatform string

const (
	DevicePlatformANDROID DevicePlatform = "ANDROID"
	DevicePlatformIOS     DevicePlatform = "IOS"
	DevicePlatformWEB     DevicePlatform = "WEB"
)

func (e *DevicePlatform) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DevicePlatform(s)
	case string:
		*e = DevicePlatform(s)
	default:
		return fmt.Errorf("unsupported scan type for DevicePlatform: %T", src)
	}
	return nil
}

type NullDevicePlatform struct {
	DevicePlatform DevicePlatform `json:"device_platform"`
	Valid          bool           `json:"valid"` // Valid is true if DevicePlatform is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDevicePlatform) Scan(value interface{}) error {
	if value == nil {
		ns.DevicePlatform, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DevicePlatform.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDevicePlatform) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DevicePlatform), nil
}

type DocOwnerType string

const (
	DocOwnerTypeDRIVER      DocOwnerType = "DRIVER"
	DocOwnerTypeVEHICLE     DocOwnerType = "VEHICLE"
	DocOwnerTypeFLEETOWNER  DocOwnerType = "FLEET_OWNER"
	DocOwnerTypeINSTITUTION DocOwnerType = "INSTITUTION"
)

func (e *DocOwnerType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocOwnerType(s)
	case string:
		*e = DocOwnerType(s)
	default:
		return fmt.Errorf("unsupported scan type for DocOwnerType: %T", src)
	}
	return nil
}

type NullDocOwnerType struct {
	DocOwnerType DocOwnerType `json:"doc_owner_type"`
	Valid        bool         `json:"valid"` // Valid is true if DocOwnerType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocOwnerType) Scan(value interface{}) error {
	if value == nil {
		ns.DocOwnerType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocOwnerType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocOwnerType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocOwnerType), nil
}

type DocStatus string

const (
	DocStatusPENDING     DocStatus = "PENDING"
	DocStatusUNDERREVIEW DocStatus = "UNDER_REVIEW"
	DocStatusAPPROVED    DocStatus = "APPROVED"
	DocStatusREJECTED    DocStatus = "REJECTED"
	DocStatusEXPIRED     DocStatus = "EXPIRED"
)

func (e *DocStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocStatus(s)
	case string:
		*e = DocStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DocStatus: %T", src)
	}
	return nil
}

type NullDocStatus struct {
	DocStatus DocStatus `json:"doc_status"`
	Valid     bool      `json:"valid"` // Valid is true if DocStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DocStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocStatus), nil
}

type DocType string

const (
	DocTypeDRIVINGLICENCE   DocType = "DRIVING_LICENCE"
	DocTypeVEHICLELIBRE     DocType = "VEHICLE_LIBRE"
	DocTypeINSURANCE        DocType = "INSURANCE"
	DocTypeANNUALINSPECTION DocType = "ANNUAL_INSPECTION"
	DocTypePOLICECLEARANCE  DocType = "POLICE_CLEARANCE"
	DocTypePHOTO            DocType = "PHOTO"
	DocTypeYANGOPROFILE     DocType = "YANGO_PROFILE"
	DocTypeTRADELICENCE     DocType = "TRADE_LICENCE"
	DocTypeTINCERTIFICATE   DocType = "TIN_CERTIFICATE"
	DocTypeOTHER            DocType = "OTHER"
)

func (e *DocType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DocType(s)
	case string:
		*e = DocType(s)
	default:
		return fmt.Errorf("unsupported scan type for DocType: %T", src)
	}
	return nil
}

type NullDocType struct {
	DocType DocType `json:"doc_type"`
	Valid   bool    `json:"valid"` // Valid is true if DocType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDocType) Scan(value interface{}) error {
	if value == nil {
		ns.DocType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DocType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDocType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DocType), nil
}

type DriverSource string

const (
	DriverSourceTAXI        DriverSource = "TAXI"
	DriverSourceYANGO       DriverSource = "YANGO"
	DriverSourceINDEPENDENT DriverSource = "INDEPENDENT"
)

func (e *DriverSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DriverSource(s)
	case string:
		*e = DriverSource(s)
	default:
		return fmt.Errorf("unsupported scan type for DriverSource: %T", src)
	}
	return nil
}

type NullDriverSource struct {
	DriverSource DriverSource `json:"driver_source"`
	Valid        bool         `json:"valid"` // Valid is true if DriverSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDriverSource) Scan(value interface{}) error {
	if value == nil {
		ns.DriverSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DriverSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDriverSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DriverSource), nil
}

type EarningKind string

const (
	EarningKindTRIP               EarningKind = "TRIP"
	EarningKindSTANDBY            EarningKind = "STANDBY"
	EarningKindREPLACEMENTPREMIUM EarningKind = "REPLACEMENT_PREMIUM"
	EarningKindBONUS              EarningKind = "BONUS"
	EarningKindPENALTY            EarningKind = "PENALTY"
	EarningKindADJUSTMENT         EarningKind = "ADJUSTMENT"
)

func (e *EarningKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EarningKind(s)
	case string:
		*e = EarningKind(s)
	default:
		return fmt.Errorf("unsupported scan type for EarningKind: %T", src)
	}
	return nil
}

type NullEarningKind struct {
	EarningKind EarningKind `json:"earning_kind"`
	Valid       bool        `json:"valid"` // Valid is true if EarningKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEarningKind) Scan(value interface{}) error {
	if value == nil {
		ns.EarningKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EarningKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEarningKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EarningKind), nil
}

type ExceptionKind string

const (
	ExceptionKindHOLIDAY   ExceptionKind = "HOLIDAY"
	ExceptionKindNOSERVICE ExceptionKind = "NO_SERVICE"
	ExceptionKindEARLYEXIT ExceptionKind = "EARLY_EXIT"
	ExceptionKindLATEENTRY ExceptionKind = "LATE_ENTRY"
)

func (e *ExceptionKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExceptionKind(s)
	case string:
		*e = ExceptionKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ExceptionKind: %T", src)
	}
	return nil
}

type NullExceptionKind struct {
	ExceptionKind ExceptionKind `json:"exception_kind"`
	Valid         bool          `json:"valid"` // Valid is true if ExceptionKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExceptionKind) Scan(value interface{}) error {
	if value == nil {
		ns.ExceptionKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExceptionKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExceptionKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExceptionKind), nil
}

type IncidentSeverity string

const (
	IncidentSeverityLOW      IncidentSeverity = "LOW"
	IncidentSeverityMEDIUM   IncidentSeverity = "MEDIUM"
	IncidentSeverityHIGH     IncidentSeverity = "HIGH"
	IncidentSeverityCRITICAL IncidentSeverity = "CRITICAL"
)

func (e *IncidentSeverity) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IncidentSeverity(s)
	case string:
		*e = IncidentSeverity(s)
	default:
		return fmt.Errorf("unsupported scan type for IncidentSeverity: %T", src)
	}
	return nil
}

type NullIncidentSeverity struct {
	IncidentSeverity IncidentSeverity `json:"incident_severity"`
	Valid            bool             `json:"valid"` // Valid is true if IncidentSeverity is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIncidentSeverity) Scan(value interface{}) error {
	if value == nil {
		ns.IncidentSeverity, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IncidentSeverity.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIncidentSeverity) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IncidentSeverity), nil
}

type IncidentSource string

const (
	IncidentSourceDRIVER      IncidentSource = "DRIVER"
	IncidentSourceAUTO        IncidentSource = "AUTO"
	IncidentSourceRIDERSOS    IncidentSource = "RIDER_SOS"
	IncidentSourceGUARDIANSOS IncidentSource = "GUARDIAN_SOS"
	IncidentSourceDISPATCHER  IncidentSource = "DISPATCHER"
)

func (e *IncidentSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IncidentSource(s)
	case string:
		*e = IncidentSource(s)
	default:
		return fmt.Errorf("unsupported scan type for IncidentSource: %T", src)
	}
	return nil
}

type NullIncidentSource struct {
	IncidentSource IncidentSource `json:"incident_source"`
	Valid          bool           `json:"valid"` // Valid is true if IncidentSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIncidentSource) Scan(value interface{}) error {
	if value == nil {
		ns.IncidentSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IncidentSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIncidentSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IncidentSource), nil
}

type IncidentStatus string

const (
	IncidentStatusSUSPECTED          IncidentStatus = "SUSPECTED"
	IncidentStatusREPORTED           IncidentStatus = "REPORTED"
	IncidentStatusDISPATCHING        IncidentStatus = "DISPATCHING"
	IncidentStatusESCALATED          IncidentStatus = "ESCALATED"
	IncidentStatusREPLACEMENTENROUTE IncidentStatus = "REPLACEMENT_EN_ROUTE"
	IncidentStatusHANDOVERDONE       IncidentStatus = "HANDOVER_DONE"
	IncidentStatusRESOLVED           IncidentStatus = "RESOLVED"
	IncidentStatusDISMISSED          IncidentStatus = "DISMISSED"
)

func (e *IncidentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IncidentStatus(s)
	case string:
		*e = IncidentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IncidentStatus: %T", src)
	}
	return nil
}

type NullIncidentStatus struct {
	IncidentStatus IncidentStatus `json:"incident_status"`
	Valid          bool           `json:"valid"` // Valid is true if IncidentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIncidentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IncidentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IncidentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIncidentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IncidentStatus), nil
}

type IncidentType string

const (
	IncidentTypeBREAKDOWN         IncidentType = "BREAKDOWN"
	IncidentTypeACCIDENT          IncidentType = "ACCIDENT"
	IncidentTypeFLATTYRE          IncidentType = "FLAT_TYRE"
	IncidentTypeFUEL              IncidentType = "FUEL"
	IncidentTypeMEDICAL           IncidentType = "MEDICAL"
	IncidentTypePOLICESTOP        IncidentType = "POLICE_STOP"
	IncidentTypeDRIVERNOSHOW      IncidentType = "DRIVER_NO_SHOW"
	IncidentTypeGPSLOST           IncidentType = "GPS_LOST"
	IncidentTypeSTATIONARYANOMALY IncidentType = "STATIONARY_ANOMALY"
	IncidentTypeHARSHEVENT        IncidentType = "HARSH_EVENT"
	IncidentTypeSOS               IncidentType = "SOS"
	IncidentTypeOTHER             IncidentType = "OTHER"
)

func (e *IncidentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IncidentType(s)
	case string:
		*e = IncidentType(s)
	default:
		return fmt.Errorf("unsupported scan type for IncidentType: %T", src)
	}
	return nil
}

type NullIncidentType struct {
	IncidentType IncidentType `json:"incident_type"`
	Valid        bool         `json:"valid"` // Valid is true if IncidentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIncidentType) Scan(value interface{}) error {
	if value == nil {
		ns.IncidentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IncidentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIncidentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IncidentType), nil
}

type InstitutionType string

const (
	InstitutionTypeSCHOOL           InstitutionType = "SCHOOL"
	InstitutionTypeUNIVERSITY       InstitutionType = "UNIVERSITY"
	InstitutionTypeGOVERNMENTOFFICE InstitutionType = "GOVERNMENT_OFFICE"
	InstitutionTypePRIVATECOMPANY   InstitutionType = "PRIVATE_COMPANY"
)

func (e *InstitutionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InstitutionType(s)
	case string:
		*e = InstitutionType(s)
	default:
		return fmt.Errorf("unsupported scan type for InstitutionType: %T", src)
	}
	return nil
}

type NullInstitutionType struct {
	InstitutionType InstitutionType `json:"institution_type"`
	Valid           bool            `json:"valid"` // Valid is true if InstitutionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInstitutionType) Scan(value interface{}) error {
	if value == nil {
		ns.InstitutionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InstitutionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInstitutionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InstitutionType), nil
}

type InvoiceStatus string

const (
	InvoiceStatusDRAFT   InvoiceStatus = "DRAFT"
	InvoiceStatusISSUED  InvoiceStatus = "ISSUED"
	InvoiceStatusPAID    InvoiceStatus = "PAID"
	InvoiceStatusOVERDUE InvoiceStatus = "OVERDUE"
	InvoiceStatusVOID    InvoiceStatus = "VOID"
)

func (e *InvoiceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoiceStatus(s)
	case string:
		*e = InvoiceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoiceStatus: %T", src)
	}
	return nil
}

type NullInvoiceStatus struct {
	InvoiceStatus InvoiceStatus `json:"invoice_status"`
	Valid         bool          `json:"valid"` // Valid is true if InvoiceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoiceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvoiceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoiceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoiceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoiceStatus), nil
}

type ManifestStatus string

const (
	ManifestStatusEXPECTED    ManifestStatus = "EXPECTED"
	ManifestStatusABSENT      ManifestStatus = "ABSENT"
	ManifestStatusONBOARD     ManifestStatus = "ON_BOARD"
	ManifestStatusDROPPEDOFF  ManifestStatus = "DROPPED_OFF"
	ManifestStatusNOSHOW      ManifestStatus = "NO_SHOW"
	ManifestStatusTRANSFERRED ManifestStatus = "TRANSFERRED"
)

func (e *ManifestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ManifestStatus(s)
	case string:
		*e = ManifestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ManifestStatus: %T", src)
	}
	return nil
}

type NullManifestStatus struct {
	ManifestStatus ManifestStatus `json:"manifest_status"`
	Valid          bool           `json:"valid"` // Valid is true if ManifestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullManifestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ManifestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ManifestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullManifestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ManifestStatus), nil
}

type NotifChannel string

const (
	NotifChannelPUSH  NotifChannel = "PUSH"
	NotifChannelSMS   NotifChannel = "SMS"
	NotifChannelEMAIL NotifChannel = "EMAIL"
	NotifChannelINAPP NotifChannel = "IN_APP"
)

func (e *NotifChannel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotifChannel(s)
	case string:
		*e = NotifChannel(s)
	default:
		return fmt.Errorf("unsupported scan type for NotifChannel: %T", src)
	}
	return nil
}

type NullNotifChannel struct {
	NotifChannel NotifChannel `json:"notif_channel"`
	Valid        bool         `json:"valid"` // Valid is true if NotifChannel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotifChannel) Scan(value interface{}) error {
	if value == nil {
		ns.NotifChannel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotifChannel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotifChannel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotifChannel), nil
}

type NotifStatus string

const (
	NotifStatusQUEUED    NotifStatus = "QUEUED"
	NotifStatusSENT      NotifStatus = "SENT"
	NotifStatusDELIVERED NotifStatus = "DELIVERED"
	NotifStatusREAD      NotifStatus = "READ"
	NotifStatusFAILED    NotifStatus = "FAILED"
)

func (e *NotifStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotifStatus(s)
	case string:
		*e = NotifStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NotifStatus: %T", src)
	}
	return nil
}

type NullNotifStatus struct {
	NotifStatus NotifStatus `json:"notif_status"`
	Valid       bool        `json:"valid"` // Valid is true if NotifStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotifStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NotifStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotifStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotifStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotifStatus), nil
}

type OfferStatus string

const (
	OfferStatusOFFERED   OfferStatus = "OFFERED"
	OfferStatusACCEPTED  OfferStatus = "ACCEPTED"
	OfferStatusDECLINED  OfferStatus = "DECLINED"
	OfferStatusEXPIRED   OfferStatus = "EXPIRED"
	OfferStatusCANCELLED OfferStatus = "CANCELLED"
)

func (e *OfferStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OfferStatus(s)
	case string:
		*e = OfferStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OfferStatus: %T", src)
	}
	return nil
}

type NullOfferStatus struct {
	OfferStatus OfferStatus `json:"offer_status"`
	Valid       bool        `json:"valid"` // Valid is true if OfferStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOfferStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OfferStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OfferStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOfferStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OfferStatus), nil
}

type OnboardingStatus string

const (
	OnboardingStatusPENDING     OnboardingStatus = "PENDING"
	OnboardingStatusUNDERREVIEW OnboardingStatus = "UNDER_REVIEW"
	OnboardingStatusAPPROVED    OnboardingStatus = "APPROVED"
	OnboardingStatusACTIVE      OnboardingStatus = "ACTIVE"
	OnboardingStatusSUSPENDED   OnboardingStatus = "SUSPENDED"
	OnboardingStatusREJECTED    OnboardingStatus = "REJECTED"
)

func (e *OnboardingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OnboardingStatus(s)
	case string:
		*e = OnboardingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OnboardingStatus: %T", src)
	}
	return nil
}

type NullOnboardingStatus struct {
	OnboardingStatus OnboardingStatus `json:"onboarding_status"`
	Valid            bool             `json:"valid"` // Valid is true if OnboardingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOnboardingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OnboardingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OnboardingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOnboardingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OnboardingStatus), nil
}

type PaymentProvider string

const (
	PaymentProviderTELEBIRR     PaymentProvider = "TELEBIRR"
	PaymentProviderCHAPA        PaymentProvider = "CHAPA"
	PaymentProviderBANKTRANSFER PaymentProvider = "BANK_TRANSFER"
	PaymentProviderWALLET       PaymentProvider = "WALLET"
)

func (e *PaymentProvider) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentProvider(s)
	case string:
		*e = PaymentProvider(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentProvider: %T", src)
	}
	return nil
}

type NullPaymentProvider struct {
	PaymentProvider PaymentProvider `json:"payment_provider"`
	Valid           bool            `json:"valid"` // Valid is true if PaymentProvider is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentProvider) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentProvider, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentProvider.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentProvider) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentProvider), nil
}

type PaymentStatus string

const (
	PaymentStatusCREATED   PaymentStatus = "CREATED"
	PaymentStatusPENDING   PaymentStatus = "PENDING"
	PaymentStatusSUCCEEDED PaymentStatus = "SUCCEEDED"
	PaymentStatusFAILED    PaymentStatus = "FAILED"
	PaymentStatusCANCELLED PaymentStatus = "CANCELLED"
	PaymentStatusREFUNDED  PaymentStatus = "REFUNDED"
)

func (e *PaymentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentStatus(s)
	case string:
		*e = PaymentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentStatus: %T", src)
	}
	return nil
}

type NullPaymentStatus struct {
	PaymentStatus PaymentStatus `json:"payment_status"`
	Valid         bool          `json:"valid"` // Valid is true if PaymentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentStatus), nil
}

type PayoutStatus string

const (
	PayoutStatusDRAFT      PayoutStatus = "DRAFT"
	PayoutStatusAPPROVED   PayoutStatus = "APPROVED"
	PayoutStatusPROCESSING PayoutStatus = "PROCESSING"
	PayoutStatusPAID       PayoutStatus = "PAID"
	PayoutStatusFAILED     PayoutStatus = "FAILED"
)

func (e *PayoutStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PayoutStatus(s)
	case string:
		*e = PayoutStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PayoutStatus: %T", src)
	}
	return nil
}

type NullPayoutStatus struct {
	PayoutStatus PayoutStatus `json:"payout_status"`
	Valid        bool         `json:"valid"` // Valid is true if PayoutStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPayoutStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PayoutStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PayoutStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPayoutStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PayoutStatus), nil
}

type PlanPeriod string

const (
	PlanPeriodWEEKLY  PlanPeriod = "WEEKLY"
	PlanPeriodMONTHLY PlanPeriod = "MONTHLY"
	PlanPeriodTERM    PlanPeriod = "TERM"
)

func (e *PlanPeriod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlanPeriod(s)
	case string:
		*e = PlanPeriod(s)
	default:
		return fmt.Errorf("unsupported scan type for PlanPeriod: %T", src)
	}
	return nil
}

type NullPlanPeriod struct {
	PlanPeriod PlanPeriod `json:"plan_period"`
	Valid      bool       `json:"valid"` // Valid is true if PlanPeriod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlanPeriod) Scan(value interface{}) error {
	if value == nil {
		ns.PlanPeriod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlanPeriod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlanPeriod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlanPeriod), nil
}

type RecordStatus string

const (
	RecordStatusDRAFT    RecordStatus = "DRAFT"
	RecordStatusACTIVE   RecordStatus = "ACTIVE"
	RecordStatusINACTIVE RecordStatus = "INACTIVE"
	RecordStatusARCHIVED RecordStatus = "ARCHIVED"
)

func (e *RecordStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecordStatus(s)
	case string:
		*e = RecordStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RecordStatus: %T", src)
	}
	return nil
}

type NullRecordStatus struct {
	RecordStatus RecordStatus `json:"record_status"`
	Valid        bool         `json:"valid"` // Valid is true if RecordStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecordStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RecordStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecordStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecordStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecordStatus), nil
}

type RiderType string

const (
	RiderTypeSTUDENT      RiderType = "STUDENT"
	RiderTypeCIVILSERVANT RiderType = "CIVIL_SERVANT"
)

func (e *RiderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiderType(s)
	case string:
		*e = RiderType(s)
	default:
		return fmt.Errorf("unsupported scan type for RiderType: %T", src)
	}
	return nil
}

type NullRiderType struct {
	RiderType RiderType `json:"rider_type"`
	Valid     bool      `json:"valid"` // Valid is true if RiderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiderType) Scan(value interface{}) error {
	if value == nil {
		ns.RiderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiderType), nil
}

type RoleName string

const (
	RoleNameSTUDENTRIDER      RoleName = "STUDENT_RIDER"
	RoleNameCIVILSERVANTRIDER RoleName = "CIVIL_SERVANT_RIDER"
	RoleNameGUARDIAN          RoleName = "GUARDIAN"
	RoleNameDRIVER            RoleName = "DRIVER"
	RoleNameFLEETOWNER        RoleName = "FLEET_OWNER"
	RoleNameINSTITUTIONADMIN  RoleName = "INSTITUTION_ADMIN"
	RoleNameDISPATCHER        RoleName = "DISPATCHER"
	RoleNameSUPPORTAGENT      RoleName = "SUPPORT_AGENT"
	RoleNameSUPERADMIN        RoleName = "SUPER_ADMIN"
)

func (e *RoleName) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RoleName(s)
	case string:
		*e = RoleName(s)
	default:
		return fmt.Errorf("unsupported scan type for RoleName: %T", src)
	}
	return nil
}

type NullRoleName struct {
	RoleName RoleName `json:"role_name"`
	Valid    bool     `json:"valid"` // Valid is true if RoleName is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRoleName) Scan(value interface{}) error {
	if value == nil {
		ns.RoleName, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RoleName.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRoleName) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RoleName), nil
}

type ScopeType string

const (
	ScopeTypeGLOBAL      ScopeType = "GLOBAL"
	ScopeTypeINSTITUTION ScopeType = "INSTITUTION"
	ScopeTypeFLEET       ScopeType = "FLEET"
	ScopeTypeZONE        ScopeType = "ZONE"
)

func (e *ScopeType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ScopeType(s)
	case string:
		*e = ScopeType(s)
	default:
		return fmt.Errorf("unsupported scan type for ScopeType: %T", src)
	}
	return nil
}

type NullScopeType struct {
	ScopeType ScopeType `json:"scope_type"`
	Valid     bool      `json:"valid"` // Valid is true if ScopeType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullScopeType) Scan(value interface{}) error {
	if value == nil {
		ns.ScopeType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ScopeType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullScopeType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ScopeType), nil
}

type SeatStatus string

const (
	SeatStatusRESERVED SeatStatus = "RESERVED"
	SeatStatusACTIVE   SeatStatus = "ACTIVE"
	SeatStatusRELEASED SeatStatus = "RELEASED"
)

func (e *SeatStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SeatStatus(s)
	case string:
		*e = SeatStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SeatStatus: %T", src)
	}
	return nil
}

type NullSeatStatus struct {
	SeatStatus SeatStatus `json:"seat_status"`
	Valid      bool       `json:"valid"` // Valid is true if SeatStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSeatStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SeatStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SeatStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSeatStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SeatStatus), nil
}

type ShiftDirection string

const (
	ShiftDirectionENTRY ShiftDirection = "ENTRY"
	ShiftDirectionEXIT  ShiftDirection = "EXIT"
)

func (e *ShiftDirection) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ShiftDirection(s)
	case string:
		*e = ShiftDirection(s)
	default:
		return fmt.Errorf("unsupported scan type for ShiftDirection: %T", src)
	}
	return nil
}

type NullShiftDirection struct {
	ShiftDirection ShiftDirection `json:"shift_direction"`
	Valid          bool           `json:"valid"` // Valid is true if ShiftDirection is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullShiftDirection) Scan(value interface{}) error {
	if value == nil {
		ns.ShiftDirection, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ShiftDirection.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullShiftDirection) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ShiftDirection), nil
}

type StandbyStatus string

const (
	StandbyStatusSCHEDULED StandbyStatus = "SCHEDULED"
	StandbyStatusONDUTY    StandbyStatus = "ON_DUTY"
	StandbyStatusACTIVATED StandbyStatus = "ACTIVATED"
	StandbyStatusCOMPLETED StandbyStatus = "COMPLETED"
	StandbyStatusNOSHOW    StandbyStatus = "NO_SHOW"
	StandbyStatusCANCELLED StandbyStatus = "CANCELLED"
)

func (e *StandbyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StandbyStatus(s)
	case string:
		*e = StandbyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for StandbyStatus: %T", src)
	}
	return nil
}

type NullStandbyStatus struct {
	StandbyStatus StandbyStatus `json:"standby_status"`
	Valid         bool          `json:"valid"` // Valid is true if StandbyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStandbyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.StandbyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StandbyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStandbyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StandbyStatus), nil
}

type SubscriptionStatus string

const (
	SubscriptionStatusPENDINGPAYMENT SubscriptionStatus = "PENDING_PAYMENT"
	SubscriptionStatusACTIVE         SubscriptionStatus = "ACTIVE"
	SubscriptionStatusPAUSED         SubscriptionStatus = "PAUSED"
	SubscriptionStatusPASTDUE        SubscriptionStatus = "PAST_DUE"
	SubscriptionStatusCANCELLED      SubscriptionStatus = "CANCELLED"
	SubscriptionStatusEXPIRED        SubscriptionStatus = "EXPIRED"
)

func (e *SubscriptionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionStatus(s)
	case string:
		*e = SubscriptionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionStatus: %T", src)
	}
	return nil
}

type NullSubscriptionStatus struct {
	SubscriptionStatus SubscriptionStatus `json:"subscription_status"`
	Valid              bool               `json:"valid"` // Valid is true if SubscriptionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionStatus), nil
}

type TicketPriority string

const (
	TicketPriorityLOW    TicketPriority = "LOW"
	TicketPriorityNORMAL TicketPriority = "NORMAL"
	TicketPriorityHIGH   TicketPriority = "HIGH"
	TicketPriorityURGENT TicketPriority = "URGENT"
)

func (e *TicketPriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketPriority(s)
	case string:
		*e = TicketPriority(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketPriority: %T", src)
	}
	return nil
}

type NullTicketPriority struct {
	TicketPriority TicketPriority `json:"ticket_priority"`
	Valid          bool           `json:"valid"` // Valid is true if TicketPriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketPriority) Scan(value interface{}) error {
	if value == nil {
		ns.TicketPriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketPriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketPriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketPriority), nil
}

type TicketStatus string

const (
	TicketStatusOPEN          TicketStatus = "OPEN"
	TicketStatusINPROGRESS    TicketStatus = "IN_PROGRESS"
	TicketStatusWAITINGONUSER TicketStatus = "WAITING_ON_USER"
	TicketStatusRESOLVED      TicketStatus = "RESOLVED"
	TicketStatusCLOSED        TicketStatus = "CLOSED"
)

func (e *TicketStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TicketStatus(s)
	case string:
		*e = TicketStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TicketStatus: %T", src)
	}
	return nil
}

type NullTicketStatus struct {
	TicketStatus TicketStatus `json:"ticket_status"`
	Valid        bool         `json:"valid"` // Valid is true if TicketStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTicketStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TicketStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TicketStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTicketStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TicketStatus), nil
}

type TripStatus string

const (
	TripStatusSCHEDULED       TripStatus = "SCHEDULED"
	TripStatusDRIVERCHECKEDIN TripStatus = "DRIVER_CHECKED_IN"
	TripStatusINPROGRESS      TripStatus = "IN_PROGRESS"
	TripStatusINCIDENT        TripStatus = "INCIDENT"
	TripStatusHANDOVER        TripStatus = "HANDOVER"
	TripStatusCOMPLETED       TripStatus = "COMPLETED"
	TripStatusCANCELLED       TripStatus = "CANCELLED"
	TripStatusABORTED         TripStatus = "ABORTED"
)

func (e *TripStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TripStatus(s)
	case string:
		*e = TripStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TripStatus: %T", src)
	}
	return nil
}

type NullTripStatus struct {
	TripStatus TripStatus `json:"trip_status"`
	Valid      bool       `json:"valid"` // Valid is true if TripStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTripStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TripStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TripStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTripStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TripStatus), nil
}

type TripStopStatus string

const (
	TripStopStatusPENDING     TripStopStatus = "PENDING"
	TripStopStatusAPPROACHING TripStopStatus = "APPROACHING"
	TripStopStatusARRIVED     TripStopStatus = "ARRIVED"
	TripStopStatusDEPARTED    TripStopStatus = "DEPARTED"
	TripStopStatusSKIPPED     TripStopStatus = "SKIPPED"
)

func (e *TripStopStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TripStopStatus(s)
	case string:
		*e = TripStopStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for TripStopStatus: %T", src)
	}
	return nil
}

type NullTripStopStatus struct {
	TripStopStatus TripStopStatus `json:"trip_stop_status"`
	Valid          bool           `json:"valid"` // Valid is true if TripStopStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTripStopStatus) Scan(value interface{}) error {
	if value == nil {
		ns.TripStopStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TripStopStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTripStopStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TripStopStatus), nil
}

type UserStatus string

const (
	UserStatusACTIVE    UserStatus = "ACTIVE"
	UserStatusSUSPENDED UserStatus = "SUSPENDED"
	UserStatusDELETED   UserStatus = "DELETED"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type VehicleClass string

const (
	VehicleClassMINIBUS VehicleClass = "MINIBUS"
	VehicleClassMIDIBUS VehicleClass = "MIDIBUS"
	VehicleClassSEDAN   VehicleClass = "SEDAN"
	VehicleClassSUV     VehicleClass = "SUV"
)

func (e *VehicleClass) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VehicleClass(s)
	case string:
		*e = VehicleClass(s)
	default:
		return fmt.Errorf("unsupported scan type for VehicleClass: %T", src)
	}
	return nil
}

type NullVehicleClass struct {
	VehicleClass VehicleClass `json:"vehicle_class"`
	Valid        bool         `json:"valid"` // Valid is true if VehicleClass is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVehicleClass) Scan(value interface{}) error {
	if value == nil {
		ns.VehicleClass, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VehicleClass.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVehicleClass) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VehicleClass), nil
}

type WaitlistStatus string

const (
	WaitlistStatusWAITING   WaitlistStatus = "WAITING"
	WaitlistStatusOFFERED   WaitlistStatus = "OFFERED"
	WaitlistStatusACCEPTED  WaitlistStatus = "ACCEPTED"
	WaitlistStatusEXPIRED   WaitlistStatus = "EXPIRED"
	WaitlistStatusCANCELLED WaitlistStatus = "CANCELLED"
)

func (e *WaitlistStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WaitlistStatus(s)
	case string:
		*e = WaitlistStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for WaitlistStatus: %T", src)
	}
	return nil
}

type NullWaitlistStatus struct {
	WaitlistStatus WaitlistStatus `json:"waitlist_status"`
	Valid          bool           `json:"valid"` // Valid is true if WaitlistStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWaitlistStatus) Scan(value interface{}) error {
	if value == nil {
		ns.WaitlistStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WaitlistStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWaitlistStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WaitlistStatus), nil
}

type Absence struct {
	ID          uuid.UUID          `json:"id"`
	RiderID     uuid.UUID          `json:"rider_id"`
	ServiceDate pgtype.Date        `json:"service_date"`
	Direction   NullShiftDirection `json:"direction"`
	Reason      pgtype.Text        `json:"reason"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type AccountBalance struct {
	ID           uuid.UUID   `json:"id"`
	Code         string      `json:"code"`
	Type         AccountType `json:"type"`
	BalanceCents interface{} `json:"balance_cents"`
}

type AuditLog struct {
	ID         int64              `json:"id"`
	ActorID    *uuid.UUID         `json:"actor_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   *uuid.UUID         `json:"entity_id"`
	Before     []byte             `json:"before"`
	After      []byte             `json:"after"`
	Ip         *netip.Addr        `json:"ip"`
	RequestID  pgtype.Text        `json:"request_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuditLogs202609 struct {
	ID         int64              `json:"id"`
	ActorID    *uuid.UUID         `json:"actor_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   *uuid.UUID         `json:"entity_id"`
	Before     []byte             `json:"before"`
	After      []byte             `json:"after"`
	Ip         *netip.Addr        `json:"ip"`
	RequestID  pgtype.Text        `json:"request_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuditLogs202610 struct {
	ID         int64              `json:"id"`
	ActorID    *uuid.UUID         `json:"actor_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   *uuid.UUID         `json:"entity_id"`
	Before     []byte             `json:"before"`
	After      []byte             `json:"after"`
	Ip         *netip.Addr        `json:"ip"`
	RequestID  pgtype.Text        `json:"request_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuditLogs202611 struct {
	ID         int64              `json:"id"`
	ActorID    *uuid.UUID         `json:"actor_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   *uuid.UUID         `json:"entity_id"`
	Before     []byte             `json:"before"`
	After      []byte             `json:"after"`
	Ip         *netip.Addr        `json:"ip"`
	RequestID  pgtype.Text        `json:"request_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuthorizedPickup struct {
	ID           uuid.UUID          `json:"id"`
	RiderID      uuid.UUID          `json:"rider_id"`
	FullName     string             `json:"full_name"`
	PhoneE164    string             `json:"phone_e164"`
	Relationship string             `json:"relationship"`
	PhotoKey     pgtype.Text        `json:"photo_key"`
	Active       bool               `json:"active"`
	AddedBy      uuid.UUID          `json:"added_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type BoardingEvent struct {
	ID               uuid.UUID          `json:"id"`
	TripID           uuid.UUID          `json:"trip_id"`
	RiderID          uuid.UUID          `json:"rider_id"`
	StopID           *uuid.UUID         `json:"stop_id"`
	Kind             BoardingKind       `json:"kind"`
	Method           BoardingMethod     `json:"method"`
	HandedToPickupID *uuid.UUID         `json:"handed_to_pickup_id"`
	RelatedTripID    *uuid.UUID         `json:"related_trip_id"`
	Location         interface{}        `json:"location"`
	DeviceRecordedAt pgtype.Timestamptz `json:"device_recorded_at"`
	ServerRecordedAt pgtype.Timestamptz `json:"server_recorded_at"`
	RecordedBy       uuid.UUID          `json:"recorded_by"`
	PhotoKey         pgtype.Text        `json:"photo_key"`
}

type CalendarException struct {
	ID            uuid.UUID          `json:"id"`
	InstitutionID *uuid.UUID         `json:"institution_id"`
	ServiceDate   pgtype.Date        `json:"service_date"`
	Kind          ExceptionKind      `json:"kind"`
	TimeOverride  pgtype.Time        `json:"time_override"`
	Note          pgtype.Text        `json:"note"`
	CreatedBy     *uuid.UUID         `json:"created_by"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Device struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	Platform   DevicePlatform     `json:"platform"`
	PushToken  pgtype.Text        `json:"push_token"`
	AppVersion pgtype.Text        `json:"app_version"`
	OsVersion  pgtype.Text        `json:"os_version"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Document struct {
	ID              uuid.UUID          `json:"id"`
	OwnerType       DocOwnerType       `json:"owner_type"`
	OwnerID         uuid.UUID          `json:"owner_id"`
	DocType         DocType            `json:"doc_type"`
	FileKey         string             `json:"file_key"`
	Sha256          []byte             `json:"sha256"`
	DocNumber       pgtype.Text        `json:"doc_number"`
	IssuedOn        pgtype.Date        `json:"issued_on"`
	ExpiresOn       pgtype.Date        `json:"expires_on"`
	Status          DocStatus          `json:"status"`
	ReviewedBy      *uuid.UUID         `json:"reviewed_by"`
	ReviewedAt      pgtype.Timestamptz `json:"reviewed_at"`
	RejectionReason pgtype.Text        `json:"rejection_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Driver struct {
	ID                    uuid.UUID          `json:"id"`
	UserID                uuid.UUID          `json:"user_id"`
	FleetOwnerID          *uuid.UUID         `json:"fleet_owner_id"`
	HomeZoneID            *uuid.UUID         `json:"home_zone_id"`
	Source                DriverSource       `json:"source"`
	LicenceNumber         string             `json:"licence_number"`
	LicenceCategory       string             `json:"licence_category"`
	LicenceExpiresOn      pgtype.Date        `json:"licence_expires_on"`
	EmergencyContactName  pgtype.Text        `json:"emergency_contact_name"`
	EmergencyContactPhone pgtype.Text        `json:"emergency_contact_phone"`
	Status                OnboardingStatus   `json:"status"`
	StudentCertified      bool               `json:"student_certified"`
	StandbyOptIn          bool               `json:"standby_opt_in"`
	RatingAvg             pgtype.Numeric     `json:"rating_avg"`
	RatingCount           int32              `json:"rating_count"`
	ApprovedBy            *uuid.UUID         `json:"approved_by"`
	ApprovedAt            pgtype.Timestamptz `json:"approved_at"`
	SuspendedReason       pgtype.Text        `json:"suspended_reason"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type DriverEarning struct {
	ID             uuid.UUID          `json:"id"`
	DriverID       uuid.UUID          `json:"driver_id"`
	TripID         *uuid.UUID         `json:"trip_id"`
	StandbyShiftID *uuid.UUID         `json:"standby_shift_id"`
	Kind           EarningKind        `json:"kind"`
	AmountCents    int64              `json:"amount_cents"`
	PayoutID       *uuid.UUID         `json:"payout_id"`
	Note           pgtype.Text        `json:"note"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type DriverVehicleAssignment struct {
	ID        uuid.UUID                        `json:"id"`
	DriverID  uuid.UUID                        `json:"driver_id"`
	VehicleID uuid.UUID                        `json:"vehicle_id"`
	Valid     pgtype.Range[pgtype.Timestamptz] `json:"valid"`
	IsPrimary bool                             `json:"is_primary"`
}

type FeatureFlag struct {
	Key       string             `json:"key"`
	Enabled   bool               `json:"enabled"`
	Rules     []byte             `json:"rules"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type FleetOwner struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	BusinessName  string             `json:"business_name"`
	Tin           pgtype.Text        `json:"tin"`
	TradeLicence  pgtype.Text        `json:"trade_licence"`
	PayoutMethod  PaymentProvider    `json:"payout_method"`
	PayoutAccount pgtype.Text        `json:"payout_account"`
	Status        OnboardingStatus   `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type GuardianLink struct {
	GuardianUserID   uuid.UUID          `json:"guardian_user_id"`
	RiderID          uuid.UUID          `json:"rider_id"`
	Relationship     string             `json:"relationship"`
	IsPrimary        bool               `json:"is_primary"`
	CanManageBilling bool               `json:"can_manage_billing"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type Incident struct {
	ID                 uuid.UUID          `json:"id"`
	TripID             *uuid.UUID         `json:"trip_id"`
	VehicleID          *uuid.UUID         `json:"vehicle_id"`
	DriverID           *uuid.UUID         `json:"driver_id"`
	Type               IncidentType       `json:"type"`
	Severity           IncidentSeverity   `json:"severity"`
	Status             IncidentStatus     `json:"status"`
	Source             IncidentSource     `json:"source"`
	Location           interface{}        `json:"location"`
	Description        pgtype.Text        `json:"description"`
	ReportedBy         *uuid.UUID         `json:"reported_by"`
	AssignedDispatcher *uuid.UUID         `json:"assigned_dispatcher"`
	OpenedAt           pgtype.Timestamptz `json:"opened_at"`
	AssignedAt         pgtype.Timestamptz `json:"assigned_at"`
	ArrivedAt          pgtype.Timestamptz `json:"arrived_at"`
	ResolvedAt         pgtype.Timestamptz `json:"resolved_at"`
	SlaMet             pgtype.Bool        `json:"sla_met"`
	Version            int64              `json:"version"`
}

type IncidentEvent struct {
	ID         int64              `json:"id"`
	IncidentID uuid.UUID          `json:"incident_id"`
	Kind       string             `json:"kind"`
	ActorID    *uuid.UUID         `json:"actor_id"`
	Payload    []byte             `json:"payload"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Institution struct {
	ID           uuid.UUID          `json:"id"`
	Name         string             `json:"name"`
	NameAm       pgtype.Text        `json:"name_am"`
	Type         InstitutionType    `json:"type"`
	Tin          pgtype.Text        `json:"tin"`
	Address      pgtype.Text        `json:"address"`
	ZoneID       *uuid.UUID         `json:"zone_id"`
	Location     interface{}        `json:"location"`
	Campus       interface{}        `json:"campus"`
	ContactName  pgtype.Text        `json:"contact_name"`
	ContactPhone pgtype.Text        `json:"contact_phone"`
	BillingMode  BillingMode        `json:"billing_mode"`
	Status       RecordStatus       `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type InstitutionSchedule struct {
	ID            uuid.UUID   `json:"id"`
	InstitutionID uuid.UUID   `json:"institution_id"`
	Label         string      `json:"label"`
	Weekday       int16       `json:"weekday"`
	EntryTime     pgtype.Time `json:"entry_time"`
	ExitTime      pgtype.Time `json:"exit_time"`
}

type Invoice struct {
	ID            uuid.UUID                 `json:"id"`
	Number        string                    `json:"number"`
	InstitutionID uuid.UUID                 `json:"institution_id"`
	Period        pgtype.Range[pgtype.Date] `json:"period"`
	SubtotalCents int64                     `json:"subtotal_cents"`
	VatCents      int64                     `json:"vat_cents"`
	TotalCents    int64                     `json:"total_cents"`
	Status        InvoiceStatus             `json:"status"`
	DueOn         pgtype.Date               `json:"due_on"`
	PdfKey        pgtype.Text               `json:"pdf_key"`
	IssuedAt      pgtype.Timestamptz        `json:"issued_at"`
	PaidAt        pgtype.Timestamptz        `json:"paid_at"`
	CreatedAt     pgtype.Timestamptz        `json:"created_at"`
}

type InvoiceLine struct {
	ID             uuid.UUID  `json:"id"`
	InvoiceID      uuid.UUID  `json:"invoice_id"`
	SubscriptionID *uuid.UUID `json:"subscription_id"`
	Description    string     `json:"description"`
	Quantity       int32      `json:"quantity"`
	UnitCents      int64      `json:"unit_cents"`
	AmountCents    int64      `json:"amount_cents"`
}

type LedgerAccount struct {
	ID        uuid.UUID          `json:"id"`
	Code      string             `json:"code"`
	Type      AccountType        `json:"type"`
	OwnerType pgtype.Text        `json:"owner_type"`
	OwnerID   *uuid.UUID         `json:"owner_id"`
	Currency  string             `json:"currency"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type LedgerEntry struct {
	ID            int64     `json:"id"`
	TransactionID uuid.UUID `json:"transaction_id"`
	AccountID     uuid.UUID `json:"account_id"`
	AmountCents   int64     `json:"amount_cents"`
}

type LedgerTransaction struct {
	ID            uuid.UUID          `json:"id"`
	Kind          string             `json:"kind"`
	ReferenceType string             `json:"reference_type"`
	ReferenceID   uuid.UUID          `json:"reference_id"`
	Description   pgtype.Text        `json:"description"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

type Notification struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	TemplateCode string             `json:"template_code"`
	Channel      NotifChannel       `json:"channel"`
	Payload      []byte             `json:"payload"`
	Priority     int16              `json:"priority"`
	Status       NotifStatus        `json:"status"`
	ProviderRef  pgtype.Text        `json:"provider_ref"`
	Attempts     int16              `json:"attempts"`
	DedupeKey    pgtype.Text        `json:"dedupe_key"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	SentAt       pgtype.Timestamptz `json:"sent_at"`
	DeliveredAt  pgtype.Timestamptz `json:"delivered_at"`
	ReadAt       pgtype.Timestamptz `json:"read_at"`
}

type NotificationTemplate struct {
	Code     string       `json:"code"`
	Channel  NotifChannel `json:"channel"`
	Language AppLanguage  `json:"language"`
	Title    pgtype.Text  `json:"title"`
	Body     string       `json:"body"`
}

type OutboxEvent struct {
	ID            int64              `json:"id"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   uuid.UUID          `json:"aggregate_id"`
	Subject       string             `json:"subject"`
	Payload       []byte             `json:"payload"`
	Headers       []byte             `json:"headers"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
}

type PaymentIntent struct {
	ID             uuid.UUID          `json:"id"`
	SubscriptionID *uuid.UUID         `json:"subscription_id"`
	InvoiceID      *uuid.UUID         `json:"invoice_id"`
	PayerUserID    *uuid.UUID         `json:"payer_user_id"`
	AmountCents    int64              `json:"amount_cents"`
	Currency       string             `json:"currency"`
	Provider       PaymentProvider    `json:"provider"`
	ProviderRef    pgtype.Text        `json:"provider_ref"`
	Status         PaymentStatus      `json:"status"`
	CheckoutUrl    pgtype.Text        `json:"checkout_url"`
	IdempotencyKey string             `json:"idempotency_key"`
	FailureReason  pgtype.Text        `json:"failure_reason"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	ConfirmedAt    pgtype.Timestamptz `json:"confirmed_at"`
}

type PaymentWebhook struct {
	ID             int64              `json:"id"`
	Provider       PaymentProvider    `json:"provider"`
	EventID        string             `json:"event_id"`
	SignatureValid bool               `json:"signature_valid"`
	Payload        []byte             `json:"payload"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
	Error          pgtype.Text        `json:"error"`
}

type Payout struct {
	ID              uuid.UUID                 `json:"id"`
	DriverID        *uuid.UUID                `json:"driver_id"`
	FleetOwnerID    *uuid.UUID                `json:"fleet_owner_id"`
	Period          pgtype.Range[pgtype.Date] `json:"period"`
	GrossCents      int64                     `json:"gross_cents"`
	CommissionCents int64                     `json:"commission_cents"`
	PenaltiesCents  int64                     `json:"penalties_cents"`
	BonusesCents    int64                     `json:"bonuses_cents"`
	NetCents        int64                     `json:"net_cents"`
	Status          PayoutStatus              `json:"status"`
	Provider        NullPaymentProvider       `json:"provider"`
	ProviderRef     pgtype.Text               `json:"provider_ref"`
	ApprovedBy      *uuid.UUID                `json:"approved_by"`
	PaidAt          pgtype.Timestamptz        `json:"paid_at"`
	CreatedAt       pgtype.Timestamptz        `json:"created_at"`
}

type Plan struct {
	ID          uuid.UUID  `json:"id"`
	Code        string     `json:"code"`
	Name        string     `json:"name"`
	Period      PlanPeriod `json:"period"`
	DiscountBps int32      `json:"discount_bps"`
	Active      bool       `json:"active"`
}

type PreTripChecklist struct {
	ID          uuid.UUID          `json:"id"`
	TripID      uuid.UUID          `json:"trip_id"`
	DriverID    uuid.UUID          `json:"driver_id"`
	Items       []byte             `json:"items"`
	Passed      bool               `json:"passed"`
	Location    interface{}        `json:"location"`
	SubmittedAt pgtype.Timestamptz `json:"submitted_at"`
}

type PricingOverride struct {
	ID             uuid.UUID                 `json:"id"`
	InstitutionID  uuid.UUID                 `json:"institution_id"`
	RouteID        *uuid.UUID                `json:"route_id"`
	SeatPriceCents int64                     `json:"seat_price_cents"`
	Valid          pgtype.Range[pgtype.Date] `json:"valid"`
	ContractRef    pgtype.Text               `json:"contract_ref"`
	CreatedAt      pgtype.Timestamptz        `json:"created_at"`
}

type PricingPolicy struct {
	ID            uuid.UUID                 `json:"id"`
	City          string                    `json:"city"`
	VehicleClass  VehicleClass              `json:"vehicle_class"`
	BaseFeeCents  int64                     `json:"base_fee_cents"`
	PerKmCents    int64                     `json:"per_km_cents"`
	PerMinCents   int64                     `json:"per_min_cents"`
	CommissionBps int32                     `json:"commission_bps"`
	MinOccupancy  int16                     `json:"min_occupancy"`
	Valid         pgtype.Range[pgtype.Date] `json:"valid"`
	CreatedBy     *uuid.UUID                `json:"created_by"`
	CreatedAt     pgtype.Timestamptz        `json:"created_at"`
}

type Rating struct {
	ID          uuid.UUID          `json:"id"`
	TripID      uuid.UUID          `json:"trip_id"`
	RaterUserID uuid.UUID          `json:"rater_user_id"`
	DriverID    uuid.UUID          `json:"driver_id"`
	Score       int16              `json:"score"`
	Tags        []string           `json:"tags"`
	Comment     pgtype.Text        `json:"comment"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Replacement struct {
	ID                  uuid.UUID          `json:"id"`
	IncidentID          uuid.UUID          `json:"incident_id"`
	OriginalTripID      uuid.UUID          `json:"original_trip_id"`
	ReplacementTripID   uuid.UUID          `json:"replacement_trip_id"`
	HandoverLocation    interface{}        `json:"handover_location"`
	ArrivedAt           pgtype.Timestamptz `json:"arrived_at"`
	HandoverCompletedAt pgtype.Timestamptz `json:"handover_completed_at"`
	RidersTransferred   int16              `json:"riders_transferred"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
}

type ReplacementOffer struct {
	ID           uuid.UUID          `json:"id"`
	IncidentID   uuid.UUID          `json:"incident_id"`
	DriverID     uuid.UUID          `json:"driver_id"`
	VehicleID    uuid.UUID          `json:"vehicle_id"`
	Score        pgtype.Numeric     `json:"score"`
	EtaS         int32              `json:"eta_s"`
	PremiumCents int64              `json:"premium_cents"`
	Status       OfferStatus        `json:"status"`
	OfferedAt    pgtype.Timestamptz `json:"offered_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	RespondedAt  pgtype.Timestamptz `json:"responded_at"`
}

type Rider struct {
	ID              uuid.UUID          `json:"id"`
	UserID          *uuid.UUID         `json:"user_id"`
	RiderType       RiderType          `json:"rider_type"`
	InstitutionID   uuid.UUID          `json:"institution_id"`
	FullName        string             `json:"full_name"`
	FullNameAm      pgtype.Text        `json:"full_name_am"`
	Grade           pgtype.Text        `json:"grade"`
	StudentNumber   pgtype.Text        `json:"student_number"`
	EmployeeNumber  pgtype.Text        `json:"employee_number"`
	PhotoKey        pgtype.Text        `json:"photo_key"`
	HomeLocation    interface{}        `json:"home_location"`
	QrSecret        []byte             `json:"qr_secret"`
	DailyPinEnabled bool               `json:"daily_pin_enabled"`
	MayWalkHome     bool               `json:"may_walk_home"`
	Status          RecordStatus       `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Route struct {
	ID            uuid.UUID          `json:"id"`
	InstitutionID uuid.UUID          `json:"institution_id"`
	ZoneID        *uuid.UUID         `json:"zone_id"`
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	VehicleClass  VehicleClass       `json:"vehicle_class"`
	Path          interface{}        `json:"path"`
	DistanceM     pgtype.Int4        `json:"distance_m"`
	DurationS     pgtype.Int4        `json:"duration_s"`
	Status        RecordStatus       `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type RouteShift struct {
	ID               uuid.UUID                 `json:"id"`
	RouteID          uuid.UUID                 `json:"route_id"`
	Direction        ShiftDirection            `json:"direction"`
	ScheduleLabel    string                    `json:"schedule_label"`
	Weekdays         []int16                   `json:"weekdays"`
	AnchorTime       pgtype.Time               `json:"anchor_time"`
	Capacity         int16                     `json:"capacity"`
	DefaultVehicleID *uuid.UUID                `json:"default_vehicle_id"`
	DefaultDriverID  *uuid.UUID                `json:"default_driver_id"`
	PricingPolicyID  *uuid.UUID                `json:"pricing_policy_id"`
	Status           RecordStatus              `json:"status"`
	Valid            pgtype.Range[pgtype.Date] `json:"valid"`
	Version          int64                     `json:"version"`
	CreatedAt        pgtype.Timestamptz        `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz        `json:"updated_at"`
}

type RouteStop struct {
	RouteID        uuid.UUID `json:"route_id"`
	Seq            int16     `json:"seq"`
	StopID         uuid.UUID `json:"stop_id"`
	PlannedOffsetS int32     `json:"planned_offset_s"`
}

type SeatAssignment struct {
	ID             uuid.UUID                 `json:"id"`
	SubscriptionID uuid.UUID                 `json:"subscription_id"`
	RouteShiftID   uuid.UUID                 `json:"route_shift_id"`
	RiderID        uuid.UUID                 `json:"rider_id"`
	StopID         uuid.UUID                 `json:"stop_id"`
	Valid          pgtype.Range[pgtype.Date] `json:"valid"`
	Status         SeatStatus                `json:"status"`
	CreatedAt      pgtype.Timestamptz        `json:"created_at"`
}

type Session struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	DeviceID         *uuid.UUID         `json:"device_id"`
	RefreshTokenHash []byte             `json:"refresh_token_hash"`
	FamilyID         uuid.UUID          `json:"family_id"`
	Ip               *netip.Addr        `json:"ip"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	RevokedReason    pgtype.Text        `json:"revoked_reason"`
	Sliding          bool               `json:"sliding"`
}

type StandbyShift struct {
	ID           uuid.UUID                        `json:"id"`
	DriverID     uuid.UUID                        `json:"driver_id"`
	VehicleID    uuid.UUID                        `json:"vehicle_id"`
	ZoneID       uuid.UUID                        `json:"zone_id"`
	ServiceDate  pgtype.Date                      `json:"service_date"`
	WindowPeriod pgtype.Range[pgtype.Timestamptz] `json:"window_period"`
	Status       StandbyStatus                    `json:"status"`
	FeeCents     int64                            `json:"fee_cents"`
	CreatedAt    pgtype.Timestamptz               `json:"created_at"`
}

type Stop struct {
	ID              uuid.UUID          `json:"id"`
	Name            string             `json:"name"`
	NameAm          pgtype.Text        `json:"name_am"`
	Landmark        pgtype.Text        `json:"landmark"`
	Location        interface{}        `json:"location"`
	GeofenceRadiusM int16              `json:"geofence_radius_m"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type Subscription struct {
	ID                 uuid.UUID                 `json:"id"`
	RiderID            uuid.UUID                 `json:"rider_id"`
	PlanID             uuid.UUID                 `json:"plan_id"`
	PayerUserID        *uuid.UUID                `json:"payer_user_id"`
	PayerInstitutionID *uuid.UUID                `json:"payer_institution_id"`
	Status             SubscriptionStatus        `json:"status"`
	Period             pgtype.Range[pgtype.Date] `json:"period"`
	AutoRenew          bool                      `json:"auto_renew"`
	PriceCents         int64                     `json:"price_cents"`
	Currency           string                    `json:"currency"`
	Quote              []byte                    `json:"quote"`
	HoldExpiresAt      pgtype.Timestamptz        `json:"hold_expires_at"`
	CancelledAt        pgtype.Timestamptz        `json:"cancelled_at"`
	CancelReason       pgtype.Text               `json:"cancel_reason"`
	Version            int64                     `json:"version"`
	CreatedAt          pgtype.Timestamptz        `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz        `json:"updated_at"`
}

type SupportTicket struct {
	ID              uuid.UUID          `json:"id"`
	RequesterUserID uuid.UUID          `json:"requester_user_id"`
	TripID          *uuid.UUID         `json:"trip_id"`
	IncidentID      *uuid.UUID         `json:"incident_id"`
	Category        string             `json:"category"`
	Subject         string             `json:"subject"`
	Status          TicketStatus       `json:"status"`
	Priority        TicketPriority     `json:"priority"`
	AssignedTo      *uuid.UUID         `json:"assigned_to"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ResolvedAt      pgtype.Timestamptz `json:"resolved_at"`
}

type TicketMessage struct {
	ID          int64              `json:"id"`
	TicketID    uuid.UUID          `json:"ticket_id"`
	AuthorID    uuid.UUID          `json:"author_id"`
	Body        string             `json:"body"`
	Attachments []string           `json:"attachments"`
	Internal    bool               `json:"internal"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Trip struct {
	ID             uuid.UUID          `json:"id"`
	RouteShiftID   uuid.UUID          `json:"route_shift_id"`
	ServiceDate    pgtype.Date        `json:"service_date"`
	Direction      ShiftDirection     `json:"direction"`
	VehicleID      uuid.UUID          `json:"vehicle_id"`
	DriverID       uuid.UUID          `json:"driver_id"`
	ParentTripID   *uuid.UUID         `json:"parent_trip_id"`
	Status         TripStatus         `json:"status"`
	PlannedStartAt pgtype.Timestamptz `json:"planned_start_at"`
	PlannedEndAt   pgtype.Timestamptz `json:"planned_end_at"`
	CheckedInAt    pgtype.Timestamptz `json:"checked_in_at"`
	ActualStartAt  pgtype.Timestamptz `json:"actual_start_at"`
	ActualEndAt    pgtype.Timestamptz `json:"actual_end_at"`
	OnBoardCount   int16              `json:"on_board_count"`
	DistanceM      pgtype.Int4        `json:"distance_m"`
	DelayS         int32              `json:"delay_s"`
	Version        int64              `json:"version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type TripManifest struct {
	TripID           uuid.UUID          `json:"trip_id"`
	RiderID          uuid.UUID          `json:"rider_id"`
	SeatAssignmentID uuid.UUID          `json:"seat_assignment_id"`
	StopID           uuid.UUID          `json:"stop_id"`
	Status           ManifestStatus     `json:"status"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type TripStop struct {
	ID               uuid.UUID          `json:"id"`
	TripID           uuid.UUID          `json:"trip_id"`
	StopID           uuid.UUID          `json:"stop_id"`
	Seq              int16              `json:"seq"`
	PlannedArrivalAt pgtype.Timestamptz `json:"planned_arrival_at"`
	EtaAt            pgtype.Timestamptz `json:"eta_at"`
	ArrivedAt        pgtype.Timestamptz `json:"arrived_at"`
	DepartedAt       pgtype.Timestamptz `json:"departed_at"`
	Status           TripStopStatus     `json:"status"`
}

type User struct {
	ID                uuid.UUID          `json:"id"`
	PhoneE164         pgtype.Text        `json:"phone_e164"`
	Email             *string            `json:"email"`
	PasswordHash      pgtype.Text        `json:"password_hash"`
	TotpSecretEnc     []byte             `json:"totp_secret_enc"`
	FullName          string             `json:"full_name"`
	FullNameAm        pgtype.Text        `json:"full_name_am"`
	PreferredLanguage AppLanguage        `json:"preferred_language"`
	PhotoKey          pgtype.Text        `json:"photo_key"`
	Status            UserStatus         `json:"status"`
	FaydaVerifiedAt   pgtype.Timestamptz `json:"fayda_verified_at"`
	LastLoginAt       pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type UserRole struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Role      RoleName           `json:"role"`
	Scope     ScopeType          `json:"scope"`
	ScopeID   *uuid.UUID         `json:"scope_id"`
	GrantedBy *uuid.UUID         `json:"granted_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Vehicle struct {
	ID             uuid.UUID          `json:"id"`
	FleetOwnerID   *uuid.UUID         `json:"fleet_owner_id"`
	OwnerDriverID  *uuid.UUID         `json:"owner_driver_id"`
	PlateNumber    string             `json:"plate_number"`
	VehicleClass   VehicleClass       `json:"vehicle_class"`
	Make           string             `json:"make"`
	Model          string             `json:"model"`
	Year           int16              `json:"year"`
	Colour         string             `json:"colour"`
	PassengerSeats int16              `json:"passenger_seats"`
	HasSeatbelts   bool               `json:"has_seatbelts"`
	HasFirstAid    bool               `json:"has_first_aid"`
	PhotoKey       pgtype.Text        `json:"photo_key"`
	Status         OnboardingStatus   `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type VehicleLocation struct {
	Time              pgtype.Timestamptz `json:"time"`
	VehicleID         uuid.UUID          `json:"vehicle_id"`
	TripID            *uuid.UUID         `json:"trip_id"`
	DriverID          *uuid.UUID         `json:"driver_id"`
	Location          interface{}        `json:"location"`
	SpeedKmh          pgtype.Float4      `json:"speed_kmh"`
	HeadingDeg        pgtype.Int2        `json:"heading_deg"`
	AccuracyM         pgtype.Float4      `json:"accuracy_m"`
	BatteryPct        pgtype.Int2        `json:"battery_pct"`
	IsOfflineBackfill bool               `json:"is_offline_backfill"`
}

type WaitlistEntry struct {
	ID             uuid.UUID          `json:"id"`
	RouteShiftID   uuid.UUID          `json:"route_shift_id"`
	RiderID        uuid.UUID          `json:"rider_id"`
	StopID         uuid.UUID          `json:"stop_id"`
	PlanID         uuid.UUID          `json:"plan_id"`
	Status         WaitlistStatus     `json:"status"`
	OfferedAt      pgtype.Timestamptz `json:"offered_at"`
	OfferExpiresAt pgtype.Timestamptz `json:"offer_expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Zone struct {
	ID         uuid.UUID          `json:"id"`
	City       string             `json:"city"`
	Name       string             `json:"name"`
	Boundary   interface{}        `json:"boundary"`
	MinStandby int16              `json:"min_standby"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
