// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phoneE164 pgtype.Text) (User, error)
	ListUserRoles(ctx context.Context, userID uuid.UUID) ([]ListUserRolesRow, error)
}

var _ Querier = (*Queries)(nil)
