// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, phone_e164, email, password_hash, totp_secret_enc, full_name, full_name_am, preferred_language, photo_key, status, fayda_verified_at, last_login_at, created_at, updated_at, deleted_at FROM users
 WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneE164,
		&i.Email,
		&i.PasswordHash,
		&i.TotpSecretEnc,
		&i.FullName,
		&i.FullNameAm,
		&i.PreferredLanguage,
		&i.PhotoKey,
		&i.Status,
		&i.FaydaVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByPhone = `-- name: GetUserByPhone :one
SELECT id, phone_e164, email, password_hash, totp_secret_enc, full_name, full_name_am, preferred_language, photo_key, status, fayda_verified_at, last_login_at, created_at, updated_at, deleted_at FROM users
 WHERE phone_e164 = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByPhone(ctx context.Context, phoneE164 pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhone, phoneE164)
	var i User
	err := row.Scan(
		&i.ID,
		&i.PhoneE164,
		&i.Email,
		&i.PasswordHash,
		&i.TotpSecretEnc,
		&i.FullName,
		&i.FullNameAm,
		&i.PreferredLanguage,
		&i.PhotoKey,
		&i.Status,
		&i.FaydaVerifiedAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listUserRoles = `-- name: ListUserRoles :many
SELECT role, scope, scope_id FROM user_roles
 WHERE user_id = $1
 ORDER BY role, scope
`

type ListUserRolesRow struct {
	Role    RoleName   `json:"role"`
	Scope   ScopeType  `json:"scope"`
	ScopeID *uuid.UUID `json:"scope_id"`
}

func (q *Queries) ListUserRoles(ctx context.Context, userID uuid.UUID) ([]ListUserRolesRow, error) {
	rows, err := q.db.Query(ctx, listUserRoles, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserRolesRow{}
	for rows.Next() {
		var i ListUserRolesRow
		if err := rows.Scan(&i.Role, &i.Scope, &i.ScopeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
