// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package apigen

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for DevicePlatform.
const (
	ANDROID DevicePlatform = "ANDROID"
	IOS     DevicePlatform = "IOS"
	WEB     DevicePlatform = "WEB"
)

// Valid indicates whether the value is a known member of the DevicePlatform enum.
func (e DevicePlatform) Valid() bool {
	switch e {
	case ANDROID:
		return true
	case IOS:
		return true
	case WEB:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusChecks.
const (
	HealthStatusChecksFail HealthStatusChecks = "fail"
	HealthStatusChecksOk   HealthStatusChecks = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatusChecks enum.
func (e HealthStatusChecks) Valid() bool {
	switch e {
	case HealthStatusChecksFail:
		return true
	case HealthStatusChecksOk:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatusStatus.
const (
	HealthStatusStatusOk          HealthStatusStatus = "ok"
	HealthStatusStatusUnavailable HealthStatusStatus = "unavailable"
)

// Valid indicates whether the value is a known member of the HealthStatusStatus enum.
func (e HealthStatusStatus) Valid() bool {
	switch e {
	case HealthStatusStatusOk:
		return true
	case HealthStatusStatusUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for JWKSKeysAlg.
const (
	EdDSA JWKSKeysAlg = "EdDSA"
)

// Valid indicates whether the value is a known member of the JWKSKeysAlg enum.
func (e JWKSKeysAlg) Valid() bool {
	switch e {
	case EdDSA:
		return true
	default:
		return false
	}
}

// Defines values for JWKSKeysCrv.
const (
	Ed25519 JWKSKeysCrv = "Ed25519"
)

// Valid indicates whether the value is a known member of the JWKSKeysCrv enum.
func (e JWKSKeysCrv) Valid() bool {
	switch e {
	case Ed25519:
		return true
	default:
		return false
	}
}

// Defines values for JWKSKeysKty.
const (
	OKP JWKSKeysKty = "OKP"
)

// Valid indicates whether the value is a known member of the JWKSKeysKty enum.
func (e JWKSKeysKty) Valid() bool {
	switch e {
	case OKP:
		return true
	default:
		return false
	}
}

// Defines values for JWKSKeysUse.
const (
	Sig JWKSKeysUse = "sig"
)

// Valid indicates whether the value is a known member of the JWKSKeysUse enum.
func (e JWKSKeysUse) Valid() bool {
	switch e {
	case Sig:
		return true
	default:
		return false
	}
}

// Defines values for Language.
const (
	Am Language = "am"
	En Language = "en"
	Om Language = "om"
)

// Valid indicates whether the value is a known member of the Language enum.
func (e Language) Valid() bool {
	switch e {
	case Am:
		return true
	case En:
		return true
	case Om:
		return true
	default:
		return false
	}
}

// Defines values for Role.
const (
	CIVILSERVANTRIDER Role = "CIVIL_SERVANT_RIDER"
	DISPATCHER        Role = "DISPATCHER"
	DRIVER            Role = "DRIVER"
	FLEETOWNER        Role = "FLEET_OWNER"
	GUARDIAN          Role = "GUARDIAN"
	INSTITUTIONADMIN  Role = "INSTITUTION_ADMIN"
	STUDENTRIDER      Role = "STUDENT_RIDER"
	SUPERADMIN        Role = "SUPER_ADMIN"
	SUPPORTAGENT      Role = "SUPPORT_AGENT"
)

// Valid indicates whether the value is a known member of the Role enum.
func (e Role) Valid() bool {
	switch e {
	case CIVILSERVANTRIDER:
		return true
	case DISPATCHER:
		return true
	case DRIVER:
		return true
	case FLEETOWNER:
		return true
	case GUARDIAN:
		return true
	case INSTITUTIONADMIN:
		return true
	case STUDENTRIDER:
		return true
	case SUPERADMIN:
		return true
	case SUPPORTAGENT:
		return true
	default:
		return false
	}
}

// Defines values for Scope.
const (
	FLEET       Scope = "FLEET"
	GLOBAL      Scope = "GLOBAL"
	INSTITUTION Scope = "INSTITUTION"
	ZONE        Scope = "ZONE"
)

// Valid indicates whether the value is a known member of the Scope enum.
func (e Scope) Valid() bool {
	switch e {
	case FLEET:
		return true
	case GLOBAL:
		return true
	case INSTITUTION:
		return true
	case ZONE:
		return true
	default:
		return false
	}
}

// Defines values for TokenPairTokenType.
const (
	Bearer TokenPairTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the TokenPairTokenType enum.
func (e TokenPairTokenType) Valid() bool {
	switch e {
	case Bearer:
		return true
	default:
		return false
	}
}

// DeviceInfo defines model for DeviceInfo.
type DeviceInfo struct {
	AppVersion *string        `json:"app_version,omitempty"`
	OsVersion  *string        `json:"os_version,omitempty"`
	Platform   DevicePlatform `json:"platform"`
	PushToken  *string        `json:"push_token,omitempty"`
}

// DevicePlatform defines model for DevicePlatform.
type DevicePlatform string

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Checks  *map[string]HealthStatusChecks `json:"checks,omitempty"`
	Service string                         `json:"service"`
	Status  HealthStatusStatus             `json:"status"`
	Version string                         `json:"version"`
}

// HealthStatusChecks defines model for HealthStatus.Checks.
type HealthStatusChecks string

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// JWKS defines model for JWKS.
type JWKS struct {
	Keys []struct {
		Alg JWKSKeysAlg `json:"alg"`
		Crv JWKSKeysCrv `json:"crv"`
		Kid string      `json:"kid"`
		Kty JWKSKeysKty `json:"kty"`
		Use JWKSKeysUse `json:"use"`

		// X Base64url public key.
		X string `json:"x"`
	} `json:"keys"`
}

// JWKSKeysAlg defines model for JWKS.Keys.Alg.
type JWKSKeysAlg string

// JWKSKeysCrv defines model for JWKS.Keys.Crv.
type JWKSKeysCrv string

// JWKSKeysKty defines model for JWKS.Keys.Kty.
type JWKSKeysKty string

// JWKSKeysUse defines model for JWKS.Keys.Use.
type JWKSKeysUse string

// Language defines model for Language.
type Language string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
	TotpCode *string             `json:"totp_code,omitempty"`
}

// Me defines model for Me.
type Me struct {
	Email      *openapi_types.Email `json:"email,omitempty"`
	FullName   string               `json:"full_name"`
	FullNameAm *string              `json:"full_name_am,omitempty"`
	Id         openapi_types.UUID   `json:"id"`

	// LinkedRiderIds Riders this user guards or is.
	LinkedRiderIds []openapi_types.UUID `json:"linked_rider_ids"`
	PhoneE164      *string              `json:"phone_e164,omitempty"`

	// PhotoUrl Short-lived signed URL.
	PhotoUrl          *string     `json:"photo_url,omitempty"`
	PreferredLanguage Language    `json:"preferred_language"`
	Roles             []RoleGrant `json:"roles"`
}

// OtpRequest defines model for OtpRequest.
type OtpRequest struct {
	// PhoneE164 Example: +251911234567
	PhoneE164 PhoneE164 `json:"phone_e164"`
}

// OtpRequested defines model for OtpRequested.
type OtpRequested struct {
	// ExpiresInS Example: 300
	ExpiresInS int `json:"expires_in_s"`

	// ResendAfterS Example: 60
	ResendAfterS int `json:"resend_after_s"`
}

// OtpVerify defines model for OtpVerify.
type OtpVerify struct {
	Code   string      `json:"code"`
	Device *DeviceInfo `json:"device,omitempty"`

	// PhoneE164 Example: +251911234567
	PhoneE164 PhoneE164 `json:"phone_e164"`
}

// PhoneE164 Example: +251911234567
type PhoneE164 = string

// Problem RFC 9457 problem details.
type Problem struct {
	// Code Stable machine-readable error code.
	Code   string  `json:"code"`
	Detail *string `json:"detail,omitempty"`
	Status int     `json:"status"`
	Title  string  `json:"title"`
	Type   string  `json:"type"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// Role defines model for Role.
type Role string

// RoleGrant defines model for RoleGrant.
type RoleGrant struct {
	Role  Role  `json:"role"`
	Scope Scope `json:"scope"`

	// ScopeId Institution, fleet or zone id; null for GLOBAL.
	ScopeId *openapi_types.UUID `json:"scope_id,omitempty"`
}

// Scope defines model for Scope.
type Scope string

// TokenPair Example: {"access_token":"eyJhbGciOiJFZERTQSIsImtpZCI6IjIwMjYtMDkifQ.e30.c2ln","expires_in":900,"refresh_token":"3q2-7wEXAMPLEonlyEXAMPLEonly","token_type":"Bearer","user":{"full_name":"Abebe Kebede","id":"01926f3a-7c1e-7d2b-9a41-5f0c3b8e2d11","linked_rider_ids":[],"phone_e164":"+251911234567","preferred_language":"am","roles":[{"role":"GUARDIAN","scope":"GLOBAL","scope_id":null}]}}
type TokenPair struct {
	// AccessToken EdDSA-signed JWT.
	AccessToken string `json:"access_token"`

	// ExpiresIn Access token lifetime in seconds.
	//
	// Example: 900
	ExpiresIn int `json:"expires_in"`

	// RefreshToken Opaque token
	RefreshToken string             `json:"refresh_token"`
	TokenType    TokenPairTokenType `json:"token_type"`
	User         Me                 `json:"user"`
}

// TokenPairTokenType defines model for TokenPair.TokenType.
type TokenPairTokenType string

// AcceptLanguage defines model for AcceptLanguage.
type AcceptLanguage = Language

// BadRequest RFC 9457 problem details.
type BadRequest = Problem

// TooManyRequests RFC 9457 problem details.
type TooManyRequests = Problem

// Unauthorized RFC 9457 problem details.
type Unauthorized = Problem

// RequestOtpParams defines parameters for RequestOtp.
type RequestOtpParams struct {
	AcceptLanguage *AcceptLanguage `json:"Accept-Language,omitempty"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshRequest

// RequestOtpJSONRequestBody defines body for RequestOtp for application/json ContentType.
type RequestOtpJSONRequestBody = OtpRequest

// VerifyOtpJSONRequestBody defines body for VerifyOtp for application/json ContentType.
type VerifyOtpJSONRequestBody = OtpVerify

// RefreshTokensJSONRequestBody defines body for RefreshTokens for application/json ContentType.
type RefreshTokensJSONRequestBody = RefreshRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetJwks Public keys that verify access tokens (Ed25519, JWKS)
	// (GET /.well-known/jwks.json)
	GetJwks(w http.ResponseWriter, r *http.Request)
	// GetHealthz Liveness probe
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// GetReadyz Readiness probe (checks dependencies such as Postgres)
	// (GET /readyz)
	GetReadyz(w http.ResponseWriter, r *http.Request)
	// Login Staff login for the web portals (email + password + TOTP)
	// (POST /v1/auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Logout Revoke the current session
	// (POST /v1/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// RequestOtp Send a 6-digit SMS OTP to a phone number
	// (POST /v1/auth/otp/request)
	RequestOtp(w http.ResponseWriter, r *http.Request, params RequestOtpParams)
	// VerifyOtp Verify an OTP and receive access and refresh tokens
	// (POST /v1/auth/otp/verify)
	VerifyOtp(w http.ResponseWriter, r *http.Request)
	// RefreshTokens Rotate a refresh token
	// (POST /v1/auth/refresh)
	RefreshTokens(w http.ResponseWriter, r *http.Request)
	// GetMe Current user's profile, roles and linked riders
	// (GET /v1/me)
	GetMe(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// GetJwks Public keys that verify access tokens (Ed25519, JWKS)
// (GET /.well-known/jwks.json)
func (_ Unimplemented) GetJwks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetHealthz Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetReadyz Readiness probe (checks dependencies such as Postgres)
// (GET /readyz)
func (_ Unimplemented) GetReadyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Login Staff login for the web portals (email + password + TOTP)
// (POST /v1/auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Logout Revoke the current session
// (POST /v1/auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RequestOtp Send a 6-digit SMS OTP to a phone number
// (POST /v1/auth/otp/request)
func (_ Unimplemented) RequestOtp(w http.ResponseWriter, r *http.Request, params RequestOtpParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// VerifyOtp Verify an OTP and receive access and refresh tokens
// (POST /v1/auth/otp/verify)
func (_ Unimplemented) VerifyOtp(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RefreshTokens Rotate a refresh token
// (POST /v1/auth/refresh)
func (_ Unimplemented) RefreshTokens(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMe Current user's profile, roles and linked riders
// (GET /v1/me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetJwks operation middleware
func (siw *ServerInterfaceWrapper) GetJwks(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJwks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadyz operation middleware
func (siw *ServerInterfaceWrapper) GetReadyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestOtp operation middleware
func (siw *ServerInterfaceWrapper) RequestOtp(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params RequestOtpParams

	headers := r.Header

	// ------------- Optional header parameter "Accept-Language" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Accept-Language")]; found {
		var AcceptLanguage AcceptLanguage
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Accept-Language", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Accept-Language", valueList[0], &AcceptLanguage, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Accept-Language", Err: err})
			return
		}

		params.AcceptLanguage = &AcceptLanguage

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestOtp(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyOtp operation middleware
func (siw *ServerInterfaceWrapper) VerifyOtp(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyOtp(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshTokens operation middleware
func (siw *ServerInterfaceWrapper) RefreshTokens(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshTokens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadyz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/.well-known/jwks.json", wrapper.GetJwks)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/otp/request", wrapper.RequestOtp)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/otp/verify", wrapper.VerifyOtp)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/refresh", wrapper.RefreshTokens)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/v1/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/v1/me", wrapper.GetMe)
	})

	return r
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type TooManyRequestsResponseHeaders struct {
	RetryAfter *int
}
type TooManyRequestsApplicationProblemPlusJSONResponse struct {
	Body Problem

	Headers TooManyRequestsResponseHeaders
}

type UnauthorizedApplicationProblemPlusJSONResponse Problem

type GetJwksRequestObject struct {
}

type GetJwksResponseObject interface {
	VisitGetJwksResponse(w http.ResponseWriter) error
}

type GetJwks200JSONResponse JWKS

func (response GetJwks200JSONResponse) VisitGetJwksResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse HealthStatus

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyzRequestObject struct {
}

type GetReadyzResponseObject interface {
	VisitGetReadyzResponse(w http.ResponseWriter) error
}

type GetReadyz200JSONResponse HealthStatus

func (response GetReadyz200JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetReadyz503JSONResponse HealthStatus

func (response GetReadyz503JSONResponse) VisitGetReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse TokenPair

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response Login400ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Login401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response Login401ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response Login429ApplicationProblemPlusJSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type LogoutRequestObject struct {
	Body *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout204Response struct {
}

func (response Logout204Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type Logout401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response Logout401ApplicationProblemPlusJSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RequestOtpRequestObject struct {
	Params RequestOtpParams
	Body   *RequestOtpJSONRequestBody
}

type RequestOtpResponseObject interface {
	VisitRequestOtpResponse(w http.ResponseWriter) error
}

type RequestOtp202JSONResponse OtpRequested

func (response RequestOtp202JSONResponse) VisitRequestOtpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type RequestOtp400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response RequestOtp400ApplicationProblemPlusJSONResponse) VisitRequestOtpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type RequestOtp429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response RequestOtp429ApplicationProblemPlusJSONResponse) VisitRequestOtpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyOtpRequestObject struct {
	Body *VerifyOtpJSONRequestBody
}

type VerifyOtpResponseObject interface {
	VisitVerifyOtpResponse(w http.ResponseWriter) error
}

type VerifyOtp200JSONResponse TokenPair

func (response VerifyOtp200JSONResponse) VisitVerifyOtpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyOtp400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response VerifyOtp400ApplicationProblemPlusJSONResponse) VisitVerifyOtpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyOtp401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response VerifyOtp401ApplicationProblemPlusJSONResponse) VisitVerifyOtpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type VerifyOtp429ApplicationProblemPlusJSONResponse struct {
	TooManyRequestsApplicationProblemPlusJSONResponse
}

func (response VerifyOtp429ApplicationProblemPlusJSONResponse) VisitVerifyOtpResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	if response.Headers.RetryAfter != nil {
		w.Header().Set("Retry-After", fmt.Sprint(*response.Headers.RetryAfter))
	}
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokensRequestObject struct {
	Body *RefreshTokensJSONRequestBody
}

type RefreshTokensResponseObject interface {
	VisitRefreshTokensResponse(w http.ResponseWriter) error
}

type RefreshTokens200JSONResponse TokenPair

func (response RefreshTokens200JSONResponse) VisitRefreshTokensResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokens401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response RefreshTokens401ApplicationProblemPlusJSONResponse) VisitRefreshTokensResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetMeRequestObject struct {
}

type GetMeResponseObject interface {
	VisitGetMeResponse(w http.ResponseWriter) error
}

type GetMe200JSONResponse Me

func (response GetMe200JSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetMe401ApplicationProblemPlusJSONResponse struct {
	UnauthorizedApplicationProblemPlusJSONResponse
}

func (response GetMe401ApplicationProblemPlusJSONResponse) VisitGetMeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetJwks Public keys that verify access tokens (Ed25519, JWKS)
	// (GET /.well-known/jwks.json)
	GetJwks(ctx context.Context, request GetJwksRequestObject) (GetJwksResponseObject, error)
	// GetHealthz Liveness probe
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
	// GetReadyz Readiness probe (checks dependencies such as Postgres)
	// (GET /readyz)
	GetReadyz(ctx context.Context, request GetReadyzRequestObject) (GetReadyzResponseObject, error)
	// Login Staff login for the web portals (email + password + TOTP)
	// (POST /v1/auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout Revoke the current session
	// (POST /v1/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// RequestOtp Send a 6-digit SMS OTP to a phone number
	// (POST /v1/auth/otp/request)
	RequestOtp(ctx context.Context, request RequestOtpRequestObject) (RequestOtpResponseObject, error)
	// VerifyOtp Verify an OTP and receive access and refresh tokens
	// (POST /v1/auth/otp/verify)
	VerifyOtp(ctx context.Context, request VerifyOtpRequestObject) (VerifyOtpResponseObject, error)
	// RefreshTokens Rotate a refresh token
	// (POST /v1/auth/refresh)
	RefreshTokens(ctx context.Context, request RefreshTokensRequestObject) (RefreshTokensResponseObject, error)
	// GetMe Current user's profile, roles and linked riders
	// (GET /v1/me)
	GetMe(ctx context.Context, request GetMeRequestObject) (GetMeResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetJwks operation middleware
func (sh *strictHandler) GetJwks(w http.ResponseWriter, r *http.Request) {
	var request GetJwksRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetJwks(ctx, request.(GetJwksRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetJwks")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetJwksResponseObject); ok {
		if err := validResponse.VisitGetJwksResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReadyz operation middleware
func (sh *strictHandler) GetReadyz(w http.ResponseWriter, r *http.Request) {
	var request GetReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetReadyz(ctx, request.(GetReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReadyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetReadyzResponseObject); ok {
		if err := validResponse.VisitGetReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(w http.ResponseWriter, r *http.Request) {
	var request LogoutRequestObject

	var body LogoutJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		if !errors.Is(err, io.EOF) {
			sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
			return
		}
	} else {
		request.Body = &body
	}

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RequestOtp operation middleware
func (sh *strictHandler) RequestOtp(w http.ResponseWriter, r *http.Request, params RequestOtpParams) {
	var request RequestOtpRequestObject

	request.Params = params

	var body RequestOtpJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RequestOtp(ctx, request.(RequestOtpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RequestOtp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RequestOtpResponseObject); ok {
		if err := validResponse.VisitRequestOtpResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// VerifyOtp operation middleware
func (sh *strictHandler) VerifyOtp(w http.ResponseWriter, r *http.Request) {
	var request VerifyOtpRequestObject

	var body VerifyOtpJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VerifyOtp(ctx, request.(VerifyOtpRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VerifyOtp")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VerifyOtpResponseObject); ok {
		if err := validResponse.VisitVerifyOtpResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshTokens operation middleware
func (sh *strictHandler) RefreshTokens(w http.ResponseWriter, r *http.Request) {
	var request RefreshTokensRequestObject

	var body RefreshTokensJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshTokens(ctx, request.(RefreshTokensRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshTokens")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RefreshTokensResponseObject); ok {
		if err := validResponse.VisitRefreshTokensResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetMe operation middleware
func (sh *strictHandler) GetMe(w http.ResponseWriter, r *http.Request) {
	var request GetMeRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetMe(ctx, request.(GetMeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetMe")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetMeResponseObject); ok {
		if err := validResponse.VisitGetMeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fp7c9pItv8qp/pO1XUq4m07MVNT9xKbZEj8GsDJ7sRZ0kgH6CB1K90tHMbDd9/qbgESCOw8Znf/2L9s",
	"pH6c/p3febbuiS+iWHDkWpHmPYmppBFqlPZXy/cx1ueUjxM6RvOEcdIkE6QBSuIRTiMkzXRYaTXOI8qf",
	"YETNhJ8kjkiT/E9lvU/FvVWV1YTFYuERiSoWXKHd+QUNuvg5QaXNL19wjdz+S+M4ZD7VTPBKLMUwxOjp",
	"JyW4eYdfaBSH6GYERrK3rfPOWavfubocvGx1zttnxCMBaspC0iTxRHAcYO34EKJEaRgiMA7tsnkwEjKi",
	"2gMsj8vwtH5UO6nV6o3Do+NnZXM8TXWiSPOwWvWIZtrsSTp8RkMWgEzl9oiex+bFROtYNSuVQPiqjCMx",
	"L6OuoJRCqoqdYk9DFo+F7dod26EWoPIli+0KTdKf4HJ/YAqYE6ls1u4LcUH5PEVVfQWs3y1Vl2qEkEVM",
	"A37xEQMMDIqORlaSLmo5L7VGGqX5mZ/eQ1/wQIEWcEeZ0dNISHNOLeeMj8s5vqWYM65xjNJIs/DIDaeJ",
	"ngjJ/sDgu/jUubSMGpx222fty36ndd7L0aG2pkNuz0dxIcnO+BFsuGBKMT72ljwAIQG/xExiAL7EALlm",
	"NFRlsljtZrVxhjPmY4ePhHUJUsQoNXOGSeN4MEOpmIMoPZbSkvGxEVqova/jkGpjWw+dyolwvRxtZiZq",
	"MtBiikULW/fxOTEnI833610+rIAXw0/oa7PQxtJGzzyJzLTW5Vn3qmN8ROfK6PVd+0VmhfUhfkUa6kkv",
	"1fomQv4E/anDKgiYUQUNr3MjlvuJKfHIyDijol22BFcojeSFuKqVMLnFE05nlIV0GGLhHrtVtYFouv5a",
	"iPXcIoxfv3vT20ZminP7l2mMCoCj4Th7gHZw1msVSu3LWX5g/eiodlI4dMqCQrymep5d4urNdeH0RGF2",
	"mGLjwmFftp3WC6rw+DCRIcTJMGQ+THFeJt4DMBux3PnMok58zwLjZCnCOn1ApaTz7QUN5EWzskF9eTwa",
	"EY8gJx4RUeE5z8WY8UxczusPIxtX74kLnqSZPilYKKZK3QkZ5EavHnokYvwc+VhPSLNWL7INoeOB88km",
	"Z9EapQH9H++rpZMP98eLnx5EeinaatMikC7wa07Jk9BZWlPLBAukHiVhOHA50/2etwNqvdKDy7E8fEnC",
	"giKsQ8anGAwkC1AOWKC2udo1rxToCVOQKJQwTqgMlAkXTBnSrgz2wc3yZPQyOdajjhRPhBaDRIYFWcBE",
	"SF0K2QwDUGzMMYCb7rmRbi2UZI9RQyxxhFJiMAgzRvC4RNUjUoSY92L7ZnZFiK8k5Q9bqsVzzZBCMZe7",
	"Fyi1iL5XOt5prHnF7E0wzMi2GbgVZtdr7N/eZV0bdmQTETVgfKByyVbDJtUbaZwtD5AHA2pyxI0ZxwUT",
	"Ns09u9vWYjukf4uSjeYFEf6rHI/JypZx++GUx2ZdW4bz3frxnNBFB13Pz2JKckWPdZSrw97ePn1fK518",
	"cId+5tUOi8+9TE23Hc7LUzg5PHoGacYNriazvqYY6g1foI2BQ0T9CeNYkkgD+8Am0mDmlIv1oFPfvSd/",
	"2mZemtHf7/J295seaH/ksW+Xq3rrzGqngro4kqgmO01ZuvePTY7zwws3FGEuL+j1b0y1M+h2ztpd4pHT",
	"ztvO+aDX7r5tZZ6+uml1zzqtS+KRs27nrX328rzd7g+u3l3aX53LXr/Tv7HleOvsomOHdnrXrf7pr3ZA",
	"7+b6+qrbH7RetS/77ne7mw4tykfW3nUblPQMDzlnV2iJ+MHBPTtoOXrggm+elh2uNNOJ+eXBKETUJoT+",
	"ITgCC34GE5hgJCS8Or960doIXS6ePhC7NjUpHIOsZEWK7C0PttSk2zmviqWaiEd+v7psFwLdN1y5pkxu",
	"lMXU91GpJfMIzl9Phq98dsVev/y93e3/1uuoTqTj3087x51PnbuLT3/XF2dTNvqtjI1q2a+HJtlc+2bS",
	"PDHOf4PQpPG5Xnp21/5b6+L6vC14OM/8ayzJDBukMr9AKm1vyiQy1jbXSRdpDXGI8AaHGBjgjA5JtXZS",
	"Px41aOmZX8PSs6A+LJ3Qw1rpaFT1G8PnWA9qtaKA23z/Ie+ltz1mQZ7hcuw0h3i/pGnWdlIyrlW15pth",
	"x+LDYrHpJPNa2GSlraNKacr0+l2/0DVmdbC5QMsuD3Z5CNkINYtsq0y5xkzZ6jDlxMmu6L3hoxrVUkDn",
	"oEIWMD52bYl52Z1xs49xFdPPCToBCpPODAHWXE+ZsKOskw/Z+wVu2VsO59y2OQA3T5vut22gtqb3E8n0",
	"vGd2ddocWrlbiSl+lr9eLv3E63d94u1TMM0oy4PaUSliPLHtN6e3VbfMCDJcGkumO+UaSSxt/uR3unal",
	"bLfd60PrumOdmZ4gtEdiDmpCJQYlX0SR2XDZg4GDAI1sEAjfMMYsBbX6k/It75uCY8RCBKbsOkok0kcQ",
	"I9Ay0ZOmffhKgEI5QwkHgsasZOLkGPkToDywA+5weMv9kCHXcCBi5GaUOZET/QlQiTBGjpJqDGAkRQRM",
	"l6EVBEA5IA9iwbiGCUq85SMmlfacODRCMCxltps6TFioy7f8lp8KPkNuTqKaYJKZRqNxAjf9UzAQK02j",
	"WHngJ1IJCTEdM24bjLf84OP/2T7oL7dJtVo/diN++Qgl87uB8JHjFz1wjz8+8WAzUbKtSZfmKO+Wf9zo",
	"vDeBRvAnIIc/QUQfy7ecrBuSVkmt606mddMk1XKtXLV9O4eb8bblarnhEr6JJWSlfIdhWJpycccrn+6m",
	"qrxskI5RF0VBP0wCdBqlvmYzhCnOjbo8sBk3UJBCUxcnzahY4oyJRIHglqDGudnXHeOhX6F+fTdN0/b1",
	"FUG9Wt3Ty/265rXtV+3op7/uXV3COxzCG5xDD3U5Z7guDqgkiqicr01kinMDANUws0VEzi4VHKQ9Kw/M",
	"zk+MluhYWR9j7N76+MrEthn/yAC9hcuv6ZBvgiYTx1etReILiSVDhHVO7FqJa87MVqR5HLi5dukOkGMp",
	"LD5MWWM3ISG9x1D78T5nM+RmprEQzADp0EuhNBXCfC+SXTfie4FcN39jofRYYopftn3778C4FYYQYIw8",
	"QO4zVNYnSqT+xKSb9oLoqNr4AWe17ewHT5vtS/+lx9YQIlXaOJb1+eeGZhkR9jPMMIOtKQYH7tx5OFXi",
	"T4AquE6ReLKLibNaxZh4JRRjl2sZ7LadaP+qf22kjCgPqBZybmPtuljyIFcr2ViYqZbg4GW31GldlGyc",
	"fTdBbnxumsrYAtku7u6HrAs24ZxydYdSwWG1BndMT9zAj0aWQbf9202n2z5Lg0refmxfmLhkCZV+IYL5",
	"11EpbaqSgKmYan+C8v/Ty7Fsi9ZySaKvYSKkQhjalsQclKaxJVKmLUxcHv54KuV624t86meKscVfGH7W",
	"5VUBh8/FeIwBMG6t9NBtW7TaSrxK5vbcTqk9POVm4/LxsH7y8KTNO+V9ZtTTdDQCS/tV3niHQ4iF1DRU",
	"cGA5AE9hqW54CoZ5O4Jjxo5EorOGtEVN8/5rufk4vW10Zhbb3zHUq4dFF9rK+DuQOBNTDMrfqKRF3kuZ",
	"tSyqfiKlyYWV22Y/fkLHFZnpLBV6oy7VWLKJKwagBTRWwRlilFCrgqsy3E9bFK88UO3JdkaXAnalY2ve",
	"609O3hcjsB5S2fgkZfHhO7zOnur90W4j02N/lNOof6VjzHXJG647km+EH1e/QVjLny1XY4KOQq6/2dP8",
	"cKeBPAAKx6WAjZmG3kUPjIxaAE1pxpNo6ErY/RyfrXv5hRRfFcquE2EDKtUQCaXhCEygieKU7kaCDLvh",
	"VCLVab1jr88EB1tFOm+3TX93r+DY/83kTcPc4fP6Sa1BspcMuU80SK1cLVdJ9suL1XcOC+9HmUB6U/Lf",
	"sPnDLeBtWj5ySzvDSok+mpo6rSjdIxuH0upyvzGkY/c4+9xirlJHw2mcmWQrUfgzSExs5kg5iDCw2bUL",
	"Zs4K7iYiRBjRiIXzlak0CgOB3au/lPtfE6T/Yzh6iXdpWzWmTH5PHrCrdnHKo3mG7CSI+zJhV4l8gX9l",
	"C+YCd/UGjIzItVkWA+thf0jGdJqmSWbB/7XF3YiF6IFtzluzcj1/sD3/rFVFaCDLw57v277/YBIT17Z0",
	"ac1GI1WKILGtUOIR+7nD6stAGrPlh4Fk4d1veTWfmkp+hqGIIwN6dn6zUgnNgIlQuvm8+rxq86NU7Pvl",
	"57ppPWoWT59YFmR+RyaxWvwzAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
